intended_hebrew = {
    "Animals_hebrew": {
        "animal": "חיה",
        "animals": "חיות",
        "alligator": "תנין",
        "alligators": "תנינים",
        "alpaca": "אלפקה",
        "alpacas": "אלפקות",
        "anaconda": "אנקונדה",
        "anacondas": "אנקונדות",
        "ant": "נמלה",
        "ants": "נמלים",
        "antelope": "אנטילופה",
        "antelopes": "אנטילופות",
        "armadillo": "ארמדיל",
        "armadillos": "ארמדילים",
        "baboon": "בבון",
        "baboons": "בבונים",
        "bat": "עטלף",
        "bats": "עטלפים",
        "bear": "דוב",
        "bears": "דובים",
        "beast": "חיה",
        "bee": "דבורה",
        "bees": "דבורים",
        "beetle": "חיפושית",
        "beetles": "חיפושיות",
        "buffalo": "תאו",
        "buffalos": "תאואים",
        "butterfly": "פרפר",
        "butterflies": "פרפרים",
        "camel": "גמל",
        "camels": "גמלים",
        "cat": "חתול",
        "cats": "חתולים",
        "caterpillar": "זחל",
        "caterpillars": "זחלים",
        "cheetah": "ברדלס",
        "cheetahs": "ברדלסים",
        "chicken": "תרנגולת",
        "chickens": "תרנגולות",
        "chimpanzee": "שימפנזה",
        "chimpanzees": "שימפנזים",
        "chinchilla": "צ'ינצ'ילה",
        "chinchillas": "צ'ינצ'ילות",
        "chipmunk": "סנאי",
        "cow": "פרה",
        "cows": "פרות",
        "cobra": "קוברה",
        "cobras": "קוברות",
        "crab": "סרטן",
        "crabs": "סרטנים",
        "cricket": "צרצר",
        "crickets": "צרצרים",
        "crocodile": "תנין",
        "crocodiles": "תנינים",
        "crow": "עורב",
        "crows": "עורבים",
        "deer": "אייל",
        "dog": "כלב",
        "dogs": "כלבים",
        "dolphin": "דולפין",
        "dolphins": "דולפינים",
        "donkey": "חמור",
        "donkeys": "חמורים",
        "dove": "יונה",
        "doves": "יונים",
        "dragon": "דרקון",
        "dragonfly": "שפירית",
        "dragonflies": "שפיריות",
        "duck": "ברווז",
        "ducks": "ברווזים",
        "dinosaur": "דינוזואר",
        "dinosaurs": "דינוזוארים",
        "eagle": "נשר",
        "eagles": "נשרים",
        "elephant": "פיל",
        "elephants": "פילים",
        "falcon": "בז",
        "falcons": "בזים",
        "ferret": "חמוס",
        "ferrets": "חמוסים",
        "fish": "דג",
        "firefly": "גחלילית",
        "fireflies": "גחליליות",
        "flamingo": "פלמינגו",
        "flamingos": "פלמינגואים",
        "fox": "שועל",
        "foxes": "שועלים",
        "frog": "צפרדע",
        "frogs": "צפרדעים",
        "giraffe": "ג'ירפה",
        "giraffes": "ג'ירפות",
        "goat": "עז",
        "goats": "עזים",
        "goose": "אווז",
        "geese": "אווזים",
        "gorilla": "גורילה",
        "gorillas": "גורילות",
        "goldfish": "דג זהב",
        "grasshopper": "חגב",
        "grasshoppers": "חגבים",
        "grizzly": "דוב גריזלי",
        "hamster": "אוגר",
        "hamsters": "אוגרים",
        "hawk": "נץ",
        "hawks": "נצים",
        "hedgehog": "קיפוד",
        "hedgehogs": "קיפודים",
        "hippo": "היפופוטם",
        "hippos": "היפופוטמים",
        "hippopotamus": "היפופוטם",
        "horse": "סוס",
        "horses": "סוסים",
        "hyena": "צבוע",
        "hyenas": "צבועים",
        "ibex": "יעל",
        "ibexes": "יעלים",
        "iguana": "איגואנה",
        "iguanas": "איגואנות",
        "jaguar": "יגואר",
        "jaguars": "יגוארים",
        "jellyfish": "מדוזה",
        "kangaroo": "קנגורו",
        "kangaroos": "קנגורואים",
        "koala": "קואלה",
        "koalas": "קואלות",
        "leopard": "נמר",
        "leopards": "נמרים",
        "lemur": "למור",
        "lemurs": "למורים",
        "lice": "כינים",
        "lion": "אריה",
        "lions": "אריות",
        "lizard": "לטאה",
        "lizards": "לטאות",
        "lobster": "לובסטר",
        "lobsters": "לובסטרים",
        "llama": "למה",
        "llamas": "למות",
        "mole": "חפרפרת",
        "moles": "חפרפרות",
        "monkey": "קוף",
        "monkeys": "קופים",
        "mongoose": "נמיה",
        "mongooses": "נמיות",
        "mosquito": "יתוש",
        "mosquitoes": "יתושים",
        "moth": "עש",
        "mouse": "עכבר",
        "mice": "עכברים",
        "nightingale": "זמיר",
        "nightingales": "זמירים",
        "octopus": "תמנון",
        "octopuses": "תמנונים",
        "ostrich": "יען",
        "ostriches": "יענים",
        "otter": "לוטרה",
        "otters": "לוטרות",
        "owl": "ינשוף",
        "owls": "ינשופים",
        "ox": "שור",
        "oxen": "שוורים",
        "panda": "פנדה",
        "pandas": "פנדות",
        "parrot": "תוכי",
        "parrots": "תוכים",
        "peacock": "טווס",
        "peacocks": "טווסים",
        "pelican": "שקנאי",
        "pelicans": "שקנאים",
        "penguin": "פינגווין",
        "penguins": "פינגווינים",
        "pig": "חזיר",
        "pigs": "חזירים",
        "pigeon": "יונה",
        "pigeons": "יונים",
        "Penguin": "פינגווין",
        "Penguins": "פינגווינים",
        "platypus": "ברווזן",
        "platypuses": "ברווזנים",
        "porcupine": "דורבן",
        "porcupines": "דורבנים",
        "puppy": "גור כלבים",
        "rabbit": "ארנב",
        "rabbits": "ארנבים",
        "raccoon": "דביבון",
        "raccoons": "דביבונים",
        "rat": "עכברוש",
        "rats": "עכברושים",
        "raven": "עורב",
        "ravens": "עורבים",
        "reindeer": "אייל",
        "rhino": "קרנף",
        "rhinos": "קרנפים",
        "scorpion": "עקרב",
        "scorpions": "עקרבים",
        "sea_lion": "אריה ים",
        "sea_lions": "אריות ים",
        "seal": "כלב ים",
        "seals": "כלבי ים",
        "seahorse": "סוסון ים",
        "seahorses": "סוסוני ים",
        "sea_urchin": "קיפוד ים",
        "sea_urchins": "קיפודי ים",
        "seagull": "שחף",
        "seagulls": "שחפים",
        "shark": "כריש",
        "sharks": "כרישים",
        "sheep": "כבשה",
        "skunk": "בואש",
        "skunks": "בואשים",
        "sloth": "עצלן",
        "sloths": "עצלנים",
        "snail": "חילזון",
        "snails": "חילזונות",
        "snake": "נחש",
        "snakey": "נחשי",
        "snakes": "נחשים",
        "songbird": "ציפור שיר",
        "songbirds": "ציפורי שיר",
        "sparrow": "דרור",
        "sparrows": "דרורים",
        "spider": "עכביש",
        "spiders": "עכבישים",
        "squid": "דיונון",
        "squids": "דיונונים",
        "squirrel": "סנאי",
        "squirrels": "סנאים",
        "starfish": "כוכב ים",
        "stingray": "טריגון",
        "stingrays": "טריגונים",
        "swan": "ברבור",
        "swans": "ברבורים",
        "swordfish": "דג חרב",
        "termite": "טרמיט",
        "termites": "טרמיטים",
        "tiger": "טיגריס",
        "tigers": "טיגריסים",
        "toad": "קרפדה",
        "toads": "קרפדות",
        "toucan": "טוקן",
        "toucans": "טוקנים",
        "turtle": "צב",
        "turtles": "צבים",
        "unicorn": "חד קרן",
        "unicorns": "חדי קרן",
        "walrus": "סוס ים",
        "walruses": "סוסי ים",
        "wasp": "צרעה",
        "wasps": "צרעות",
        "whale": "לוויתן",
        "whales": "לוויתנים",
        "wolf": "זאב",
        "wolves": "זאבים",
        "zebra": "זברה",
        "zebras": "זברות"
    },
    "Transport_hebrew": {
        "ambulance": "אמבולנס",
        "ambulances": "אמבולנסים",
        "car": "מכונית",
        "cars": "מכוניות",
        "bus": "אוטובוס",
        "buses": "אוטובוסים",
        "train": "רכבת",
        "trains": "רכבות",
        "truck": "משאית",
        "trucks": "משאיות",
        "van": "וואן",
        "vans": "וואנים",
        "taxi": "מונית",
        "taxis": "מוניות",
        "motorcycle": "אופנוע",
        "motorcycles": "אופנועים",
        "bike": "אופניים",
        "bikes": "אופניים",
        "bicycle": "אופניים",
        "bicycles": "אופניים",
        "scooter": "קטנוע",
        "scooters": "קטנועים",
        "skateboard": "סקייטבורד",
        "skateboards": "סקייטבורדים",
        "subway": "רכבת תחתית",
        "subways": "רכבות תחתיות",
        "tram": "חשמלית",
        "trams": "חשמליות",
        "metro": "מטרו",
        "metros": "מטרו",
        "ferry": "מעבורת",
        "ferries": "מעבורות",
        "boat": "סירה",
        "boats": "סירות",
        "ship": "ספינה",
        "ships": "ספינות",
        "yacht": "יאכטה",
        "yachts": "יאכטות",
        "canoe": "קאנו",
        "canoes": "קאנו",
        "kayak": "קיאק",
        "kayaks": "קיאקים",
        "helicopter": "מסוק",
        "helicopters": "מסוקים",
        "plane": "מטוס",
        "planes": "מטוסים",
        "airplane": "מטוס",
        "airplanes": "מטוסים",
        "jet": "מטוס סילון",
        "jets": "מטוסי סילון",
        "glider": "דאון",
        "gliders": "דאונים",
        "spaceship": "חללית",
        "spaceships": "חלליות",
        "rocket": "טיל",
        "rockets": "טילים",
        "hovercraft": "רחפת",
        "hovercrafts": "רחפות",
        "minivan": "מיניוואן",
        "minivans": "מיניוואנים",
        "pickup": "טנדר",
        "pickups": "טנדרים",
        "suv": "רכב שטח",
        "suvs": "רכבי שטח",
        "lorry": "משאית",
        "lorries": "משאיות",
        "trolley": "עגלה",
        "trolleys": "עגלות",
        "rickshaw": "ריקשה",
        "rickshaws": "ריקשות",
        "wagon": "עגלה",
        "wagons": "עגלות",
        "caravan": "קרוואן",
        "caravans": "קרוואנים",
        "camper": "קרוואן",
        "campers": "קרוואנים",
        "motorhome": "קרוואן",
        "motorhomes": "קרוואנים",
        "taxicab": "מונית",
        "taxicabs": "מוניות",
        "sailboat": "סירת מפרש",
        "sailboats": "סירות מפרש",
        "container_ship": "אוניית מכולות",
        "container_ships": "אוניות מכולות",
        "cargo_ship": "אוניית משא",
        "cargo_ships": "אוניות משא",
        "freight_train": "רכבת משא",
        "freight_trains": "רכבות משא",
        "bullet_train": "רכבת מהירה",
        "bullet_trains": "רכבות מהירות",
        "electric_car": "רכב חשמלי",
        "electric_cars": "רכבים חשמליים",
        "hybrid_car": "רכב היברידי",
        "hybrid_cars": "רכבים היברידיים",
        "self-driving_car": "רכב אוטונומי",
        "self-driving_cars": "רכבים אוטונומיים",
        "electric_scooter": "קורקינט חשמלי",
        "electric_scooters": "קורקינטים חשמליים",
        "electric_bike": "אופניים חשמליים",
        "electric_bikes": "אופניים חשמליים",
        "sail": "להפליג",
        "drive": "לנהוג",
        "driver": "נהג",
        "drivers": "נהגים",
        "passenger": "נוסע",
        "passengers": "נוסעים",
        "pilot": "טייס",
        "pilots": "טייסים",
        "mechanic": "מכונאי",
        "mechanics": "מכונאים",
        "chauffeur": "נהג פרטי",
        "chauffeurs": "נהגים פרטיים",
        "navigator": "נווט",
        "navigators": "נווטים",
        "station": "תחנה",
        "stations": "תחנות",
        "terminal": "טרמינל",
        "terminals": "טרמינלים",
        "runway": "מסלול המראה",
        "runways": "מסלולי המראה",
        "port": "נמל",
        "ports": "נמלים",
        "harbor": "מעגן",
        "harbors": "מעגנים",
        "garage": "מוסך",
        "garages": "מוסכים",
        "highway": "כביש מהיר",
        "highways": "כבישים מהירים",
        "road": "כביש",
        "roads": "כבישים",
        "street": "רחוב",
        "streets": "רחובות",
        "lane": "נתיב",
        "lanes": "נתיבים",
        "avenue": "שדרה",
        "avenues": "שדרות",
        "intersection": "צומת",
        "intersections": "צמתים",
        "crosswalk": "מעבר חצייה",
        "crosswalks": "מעברי חצייה",
        "traffic_light": "רמזור",
        "traffic_lights": "רמזורים",
        "stop_sign": "תמרור עצור",
        "stop_signs": "תמרורי עצור",
        "roundabout": "כיכר תנועה",
        "roundabouts": "כיכרות תנועה",
        "bridge": "גשר",
        "bridges": "גשרים",
        "tunnel": "מנהרה",
        "tunnels": "מנהרות",
        "railway": "מסילת רכבת",
        "railways": "מסילות רכבת",
        "railroad": "פסי רכבת",
        "railroads": "פסי רכבת",
        "track": "מסילה",
        "tracks": "מסילות",
        "bike_lane": "שביל אופניים",
        "bike_lanes": "שבילי אופניים",
        "flight": "טיסה",
        "flights": "טיסות",
        "boarding_pass": "כרטיס עלייה למטוס",
        "boarding_passes": "כרטיסי עלייה למטוס",
        "ticket": "כרטיס",
        "tickets": "כרטיסים",
        "fare": "דמי נסיעה",
        "fares": "דמי נסיעה",
        "transport": "תחבורה",
        "transportation": "תחבורה",
        "delivery": "משלוח",
        "deliveries": "משלוחים",
        "freight": "מטען",
        "cargo": "מטען",
        "shipment": "משלוח",
        "shipments": "משלוחים",
        "commute": "נסיעה יומית",
        "commutes": "נסיעות יומיות",
        "journey": "מסע",
        "journeys": "מסעות",
        "landing": "נחיתה",
        "takeoff": "המראה",
        "takeoffs": "המראות",
        "boarding": "עלייה למטוס",
        "trip": "טיול",
        "trips": "טיולים",
        "travel": "נסיעה",
        "travels": "נסיעות",
        "transit": "מעבר",
        "route": "מסלול",
        "routes": "מסלולים",
        "itinerary": "מסלול נסיעה",
        "itineraries": "מסלולי נסיעה",
        "departure": "יציאה",
        "departures": "יציאות",
        "arrival": "הגעה",
        "arrivals": "הגעות",
        "delay": "עיכוב",
        "delays": "עיכובים",
        "schedule": "לוח זמנים",
        "schedules": "לוחות זמנים"
    },
    "Clothing_hebrew": {
        "backpack": "תרמיל גב",
        "backpacks": "תרמילים",
        "belt": "חגורה",
        "belts": "חגורות",
        "beanie": "כובע",
        "beanies": "כובעים",
        "blazer": "בלייזר",
        "blazers": "בלייזרים",
        "blouse": "חולצה",
        "blouses": "חולצות",
        "boots": "מגפיים",
        "bra": "חזייה",
        "bras": "חזיות",
        "briefs": "תחתונים",
        "cape": "גלימה",
        "capes": "גלימות",
        "cardigan": "קרדיגן",
        "cardigans": "קרדיגנים",
        "coat": "מעיל",
        "coats": "מעילים",
        "corset": "מחוך",
        "corsets": "מחוכים",
        "cufflinks": "חפתים",
        "dress": "שמלה",
        "dresses": "שמלות",
        "earrings": "עגילים",
        "espadrilles": "נעלי אספדריל",
        "flip-flops": "כפכפים",
        "gown": "שמלה",
        "gowns": "שמלות",
        "glasses": "משקפיים",
        "glove": "כפפה",
        "gloves": "כפפות",
        "hat": "כובע",
        "hats": "כובעים",
        "handbag": "תיק יד",
        "handbags": "תיקי יד",
        "heel": "עקב",
        "heels": "עקבים",
        "helmet": "קסדה",
        "helmets": "קסדות",
        "hoodie": "קפוצ'ון",
        "hoodies": "קפוצ'ונים",
        "jacket": "ז׳קט",
        "jackets": "ז׳קטים",
        "jeans": "ג׳ינס",
        "jumpsuit": "אוברול",
        "jumpsuits": "אוברולים",
        "kimono": "קימונו",
        "kimonos": "קימונו",
        "leggings": "טייץ",
        "mask": "מסכה",
        "masks": "מסכות",
        "mittens": "כפפות",
        "necklace": "שרשרת",
        "necklaces": "שרשראות",
        "overall": "סרבל",
        "overalls": "סרבל",
        "overcoat": "מעיל",
        "overcoats": "מעילים",
        "pants": "מכנסיים",
        "pajama": "פיג׳מה",
        "pajamas": "פיג׳מה",
        "panties": "תחתונים",
        "poncho": "פונצ'ו",
        "ponchos": "פונצ'ו",
        "purse": "ארנק",
        "purses": "ארנקים",
        "raincoat": "מעיל גשם",
        "raincoats": "מעילי גשם",
        "ring": "טבעת",
        "rings": "טבעות",
        "robe": "חלוק",
        "robes": "חלוקים",
        "sandal": "סנדל",
        "sandals": "סנדלים",
        "satchel": "תיק",
        "satchels": "תיקי יד",
        "scarf": "צעיף",
        "scarves": "צעיפים",
        "shirt": "חולצה",
        "shirts": "חולצות",
        "shoe": "נעל",
        "shoes": "נעליים",
        "shorts": "מכנסיים קצרים",
        "skirt": "חצאית",
        "skirts": "חצאיות",
        "slipper": "נעל בית",
        "slippers": "נעלי בית",
        "sleepwear": "הלבשת לילה",
        "sneaker": "נעל התעמלות",
        "sneakers": "נעלי ספורט",
        "socks": "גרביים",
        "suit": "חליפה",
        "suits": "חליפות",
        "sunglasses": "משקפי שמש",
        "sweater": "סוודר",
        "sweaters": "סוודרים",
        "t-shirt": "חולצת טי",
        "t-shirts": "חולצות טי",
        "tank_top": "גופייה",
        "tank_tops": "גופיות",
        "thobe": "חולצה",
        "tie": "עניבה",
        "ties": "עניבות",
        "tights": "גרביונים",
        "tracksuit": "אימונית",
        "tracksuits": "חליפות טרנינג",
        "tunic": "טוניקה",
        "tunics": "טוניקות",
        "turban": "טורבן",
        "turbans": "טורבנים",
        "tuxedo": "חליפת ערב",
        "tuxedos": "טוקסידו",
        "uniform": "מדים",
        "uniforms": "מדים",
        "veil": "צעיף",
        "veils": "צעיפים",
        "vest": "אפודה",
        "vests": "אפודות",
        "wallet": "ארנק",
        "wallets": "ארנקים",
        "watch": "שעון",
        "watches": "שעונים",
        "windbreaker": "מעיל רוח",
        "windbreakers": "מעילי רוח",
        "wristband": "צמיד",
        "wristbands": "צמידים"
    },
    "Food_hebrew": {
        "almond": "שקד",
        "almonds": "שקדים",
        "apple": "תפוח",
        "apples": "תפוחים",
        "avocado": "אבוקדו",
        "avocados": "אבוקדו",
        "artichoke": "ארטישוק",
        "asparagus": "אספרגוס",
        "bacon": "בייקון",
        "banana": "בננה",
        "bananas": "בננות",
        "bagel": "בייגל",
        "baguette": "בגט",
        "barley": "שעורה",
        "basil": "בזיליקום",
        "beans": "שעועית",
        "beef": "בקר",
        "blackberry": "אוכמניות",
        "blackberries": "אוכמניות",
        "blueberry": "אוכמניות",
        "blueberries": "אוכמניות",
        "bread": "לחם",
        "broccoli": "ברוקולי",
        "burger": "המבורגר",
        "burgers": "המבורגרים",
        "butter": "חמאה",
        "cabbage": "כרוב",
        "cake": "עוגה",
        "cakes": "עוגות",
        "candy": "ממתק",
        "candies": "ממתקים",
        "carrot": "גזר",
        "carrots": "גזרים",
        "caramel": "קרמל",
        "cashew": "קשיו",
        "cashews": "קשיו",
        "cauliflower": "כרובית",
        "cereal": "דגני בוקר",
        "cherry": "דובדבן",
        "cherries": "דובדבנים",
        "cheese": "גבינה",
        "chips": "צ'יפס",
        "chickpea": "חומוס",
        "chocolate": "שוקולד",
        "cinnamon": "קינמון",
        "coconut": "קוקוס",
        "coconuts": "קוקוסים",
        "coffee": "קפה",
        "cookie": "עוגייה",
        "cookies": "עוגיות",
        "corn": "תירס",
        "cracker": "קרקר",
        "crackers": "קרקרים",
        "crepe": "קרפ",
        "croissant": "קרואסון",
        "cucumber": "מלפפון",
        "cucumbers": "מלפפונים",
        "donut": "סופגנייה",
        "donuts": "סופגניות",
        "egg": "ביצה",
        "eggs": "ביצים",
        "eggplant": "חציל",
        "eggplants": "חצילים",
        "fish": "דג",
        "fries": "צ'יפס",
        "garlic": "שום",
        "ginger": "ג'ינג'ר",
        "grape": "ענב",
        "grapes": "ענבים",
        "grapefruit": "אשכוליות",
        "ham": "בשר חזיר",
        "hamburger": "המבורגר",
        "hamburgers": "המבורגרים",
        "hazelnut": "אגוז לוז",
        "hazelnuts": "אגוזי לוז",
        "honey": "דבש",
        "hotdog": "נקניקייה",
        "hotdogs": "נקניקיות",
        "ice cream": "גלידה",
        "ice": "קרח",
        "jam": "ריבה",
        "jelly": "ג'לי",
        "juice": "מיץ",
        "ketchup": "קטשופ",
        "kebab": "קבב",
        "kiwi": "קיווי",
        "kiwis": "קיווי",
        "lasagna": "לזניה",
        "lentil": "עדשים",
        "licorice": "ליקריץ",
        "lemon": "לימון",
        "lemons": "לימונים",
        "lettuce": "חסה",
        "lime": "ליים",
        "lobster": "לובסטר",
        "lobsters": "לובסטרים",
        "macadamia": "מקדמיה",
        "macaroni": "מקרוני",
        "macaron": "מקרון",
        "mayonnaise": "מיונז",
        "meatball": "כדור בשר",
        "mint": "נענע",
        "mango": "מנגו",
        "mangoes": "מנגו",
        "mangos": "מנגו",
        "meat": "בשר",
        "melon": "מלון",
        "melons": "מלונים",
        "milk": "חלב",
        "mousse": "מוס",
        "muffin": "מאפין",
        "muffins": "מאפינס",
        "mushroom": "פטרייה",
        "mushrooms": "פטריות",
        "mustard": "חרדל",
        "noodle": "אטריות",
        "noodles": "אטריות",
        "nut": "אגוז",
        "nuts": "אגוזים",
        "oat": "שיבולת שועל",
        "oats": "שיבולת שועל",
        "okra": "במיה",
        "oregano": "אורגנו",
        "oyster": "צדפה",
        "oatmeal": "שיבולת שועל",
        "olive": "זית",
        "olives": "זיתים",
        "onion": "בצל",
        "onions": "בצלים",
        "orange": "תפוז",
        "oranges": "תפוזים",
        "pancake": "פנקייק",
        "pancakes": "פנקייקים",
        "pasta": "פסטה",
        "pastry": "מאפה",
        "peach": "אפרסק",
        "peaches": "אפרסקים",
        "peanut": "בוטן",
        "peanuts": "בוטנים",
        "pear": "אגס",
        "pears": "אגסים",
        "peas": "אפונה",
        "pepper": "פלפל",
        "peppers": "פלפלים",
        "pecan": "פקאן",
        "pesto": "פסטו",
        "pickle": "מלפפון חמוץ",
        "pickles": "חמוצים",
        "pistachio": "פיסטוק",
        "pie": "פאי",
        "pies": "פשטידות",
        "pineapple": "אננס",
        "pineapples": "אננסים",
        "pizza": "פיצה",
        "plum": "שזיף",
        "plums": "שזיפים",
        "pork": "חזיר",
        "popcorn": "פופקורן",
        "potato": "תפוח אדמה",
        "potatoes": "תפוחי אדמה",
        "pumpkin": "דלעת",
        "pretzel": "בייגלה",
        "pretzels": "בייגלה",
        "raisin": "צימוק",
        "raisins": "צימוקים",
        "raspberry": "פטל",
        "raspberries": "פטל",
        "rice": "אורז",
        "salad": "סלט",
        "salmon": "סלמון",
        "sandwich": "כריך",
        "sandwiches": "כריכים",
        "sausage": "נקניק",
        "sausages": "נקניקים",
        "shrimp": "שרימפס",
        "smoothie": "שייק",
        "snack": "חטיף",
        "snacks": "חטיפים",
        "soda": "סודה",
        "soup": "מרק",
        "spinach": "תרד",
        "steak": "סטייק",
        "strawberry": "תות",
        "strawberries": "תותים",
        "sugar": "סוכר",
        "syrup": "סירופ",
        "sushi": "סושי",
        "sweet potato": "בטטה",
        "taco": "טאקו",
        "tahini": "טחינה",
        "tea": "תה",
        "tomato": "עגבנייה",
        "tomatoes": "עגבניות",
        "tofu": "טופו",
        "tuna": "טונה",
        "turkey": "הודו",
        "tiramisu": "טירמיסו",
        "tortilla": "טורטייה",
        "vinegar": "חומץ",
        "waffle": "וופל",
        "waffles": "וופלים",
        "walnut": "אגוז מלך",
        "walnuts": "אגוזי מלך",
        "water": "מים",
        "watermelon": "אבטיח",
        "watermelons": "אבטיחים",
        "whipped cream": "קצפת",
        "yogurt": "יוגורט",
        "Yolk": "חלמון",
        "Zucchini": "קישוא"
    },
    "Body_parts_hebrew": {
        "abdomen": "בטן",
        "ankle": "קרסול",
        "ankles": "קרסוליים",
        "appendix": "תוספתן",
        "arm": "זרוע",
        "arms": "זרועות",
        "artery": "עורק",
        "arteries": "עורקים",
        "belly": "בטן",
        "belly button": "טבור",
        "bladder": "שלפוחית השתן",
        "blood": "דם",
        "bone": "עצם",
        "bones": "עצמות",
        "brain": "מוח",
        "calf": "שוק",
        "calves": "שוקיים",
        "cartilage": "סחוס",
        "cheek": "לחי",
        "cheeks": "לחיים",
        "chest": "חזה",
        "chin": "סנטר",
        "ear": "אוזן",
        "ears": "אוזניים",
        "eardrum": "עור התוף",
        "elbow": "מרפק",
        "elbows": "מרפקים",
        "eye": "עין",
        "eyes": "עיניים",
        "eyebrow": "גבה",
        "eyebrows": "גבות",
        "eyelash": "ריס",
        "eyelashes": "ריסים",
        "eyeball": "גלגל עין",
        "eyeballs": "גלגלי עיניים",
        "finger": "אצבע",
        "fingers": "אצבעות",
        "foot": "כף רגל",
        "feet": "רגליים",
        "forehead": "מצח",
        "gallbladder": "כיס המרה",
        "genital": "איבר מין",
        "genitals": "איברי מין",
        "groin": "מפשעה",
        "gums": "חניכיים",
        "hand": "יד",
        "hands": "ידיים",
        "hair": "שיער",
        "head": "ראש",
        "hips": "ירכיים",
        "jaw": "לסת",
        "kidney": "כליה",
        "kidneys": "כליות",
        "knee": "ברך",
        "knees": "ברכיים",
        "larynx": "גרון",
        "leg": "רגל",
        "legs": "רגליים",
        "ligament": "רצועה",
        "lip": "שפה",
        "lips": "שפתיים",
        "liver": "כבד",
        "lung": "ריאה",
        "lungs": "ריאות",
        "mouth": "פה",
        "muscle": "שריר",
        "muscles": "שרירים",
        "nail": "ציפורן",
        "nails": "ציפורניים",
        "navel": "טבור",
        "neck": "צוואר",
        "nerve": "עצב",
        "nerves": "עצבים",
        "nostril": "נחיר",
        "nostrils": "נחיריים",
        "ovary": "שחלה",
        "ovaries": "שחלות",
        "palms": "כפות ידיים",
        "pancreas": "לבלב",
        "pelvis": "אגן",
        "penis": "פין",
        "pupil": "אישון",
        "retina": "רשתית",
        "rib": "צלע",
        "ribs": "צלעות",
        "scalp": "קרקפת",
        "scrotum": "שק האשכים",
        "shoulder": "כתף",
        "shoulders": "כתפיים",
        "shin": "שוק",
        "shins": "שוקיים",
        "skin": "עור",
        "skull": "גולגולת",
        "spine": "עמוד שדרה",
        "spleen": "טחול",
        "stomach": "קיבה",
        "teeth": "שיניים",
        "tendon": "גיד",
        "thigh": "ירך",
        "thighs": "ירכיים",
        "throat": "גרון",
        "thumb": "אגודל",
        "thumbs": "אגודלים",
        "toe": "אצבע",
        "toes": "אצבעות רגליים",
        "tongue": "לשון",
        "tonsils": "שקדים",
        "tooth": "שן",
        "trachea": "קנה הנשימה",
        "ureter": "שופכן",
        "urethra": "שופכה",
        "uterus": "רחם",
        "uvula": "ענבל",
        "vein": "וריד",
        "veins": "ורידים",
        "vocal cords": "מיתרי קול",
        "waist": "מותן",
        "wrist": "פרק כף היד",
        "wrists": "פרקי יד"
    },

    "sports_hebrew" : {
        "archer": "קשת",
        "archers": "קשתים",
        "archery": "חץ וקשת",
        "athlete": "אתלט",
        "athletes": "אתלטים",
        "badminton": "בדמינטון",
        "ball": "כדור",
        "balls": "כדורים",
        "baseball": "בייסבול",
        "baseballs": "כדורי בייסבול",
        "bat": "מחבט",
        "bats": "מחבטים",
        "basket": "סל",
        "baskets": "סלים",
        "basketball": "כדורסל",
        "basketballs": "כדורי סל",
        "biker": "רוכב אופניים",
        "bikers": "רוכבי אופניים",
        "billiard": "ביליארד",
        "billiards": "ביליארד",
        "bleacher": "יציע",
        "bleachers": "יציעים",
        "board": "לוח",
        "boards": "לוחות",
        "boat": "סירה",
        "boats": "סירות",
        "bow": "קשת",
        "bows": "קשתות",
        "bowling": "באולינג",
        "boxer": "מתאגרף",
        "boxers": "מתאגרפים",
        "boxing": "איגרוף",
        "captain": "קפטן",
        "captains": "קפטנים",
        "catcher": "תופס",
        "catchers": "תופסים",
        "champion": "אלוף",
        "champions": "אלופים",
        "cheer": "עידוד",
        "cheerleader": "מעודדת",
        "cheerleaders": "מעודדות",
        "climber": "מטפס",
        "climbers": "מטפסים",
        "climbing": "טיפוס",
        "crossfit": "קרוספיט",
        "coach": "מאמן",
        "coaches": "מאמנים",
        "competition": "תחרות",
        "competitions": "תחרויות",
        "crew": "צוות",
        "crews": "צוותים",
        "cyclist": "רוכב אופניים",
        "cyclists": "רוכבי אופניים",
        "cycling": "לרכב",
        "dart": "חץ",
        "darts": "חיצים",
        "diver": "צוללן",
        "divers": "צוללנים",
        "diving": "לצלול",
        "equipment": "ציוד",
        "fencer": "סייף",
        "fencers": "סייפים",
        "fencing": "סיף",
        "field": "מגרש",
        "fields": "מגרשים",
        "fighter": "לוחם",
        "fighters": "לוחמים",
        "fishing": "דיג",
        "football": "כדורגל",
        "footballs": "כדורי רגל",
        "game": "משחק",
        "games": "משחקים",
        "goal": "שער",
        "goals": "שערים",
        "goalkeeper": "שוער",
        "goalkeepers": "שוערים",
        "goggles": "משקפי מגן",
        "golf": "גולף",
        "golfs": "גולף",
        "golfer": "שחקן גולף",
        "golfers": "שחקני גולף",
        "gym": "חדר כושר",
        "gyms": "חדרי כושר",
        "gymnast": "מתעמל",
        "gymnasts": "מתעמלים",
        "gymnastics": "התעמלות",
        "helmet": "קסדה",
        "helmets": "קסדות",
        "hiker": "מטייל",
        "hikers": "מטיילים",
        "hiking": "לטייל",
        "hockey": "הוקי",
        "horse": "סוס",
        "horses": "סוסים",
        "ice hockey": "הוקי קרח",
        "ice skating": "החלקה על הקרח",
        "javelin": "כידון",
        "javelins": "כידונים",
        "jogger": "רץ",
        "joggers": "רצים",
        "jogging": "לרוץ",
        "judoka": "ג'ודוקא",
        "judokas": "ג'ודוקאים",
        "judo": "ג'ודו",
        "jump": "קפיצה",
        "jumps": "קפיצות",
        "judge": "שופט",
        "jiujitsu": "ג'יו ג'יטסו",
        "karate": "קראטה",
        "kick": "בעיטה",
        "kicks": "בעיטות",
        "kicking": "בועט",
        "kicker": "בועט",
        "kickers": "בועטים",
        "lacrosse": "לאקרוס",
        "league": "ליגה",
        "leagues": "ליגות",
        "loser": "מפסיד",
        "losers": "מפסידים",
        "martial art": "אמנות לחימה",
        "martial arts": "אמנויות לחימה",
        "match": "קרב",
        "matches": "משחקים",
        "medal": "מדליה",
        "medals": "מדליות",
        "mountain biking": "רכיבת שטח",
        "net": "רשת",
        "nets": "רשתות",
        "olympics": "אולימפיאדה",
        "paddle": "משוט",
        "paddles": "משוטים",
        "parachute": "מצנח",
        "parachutes": "מצנחים",
        "paragliding": "רחיפה",
        "parkour": "פארקור",
        "penalty": "עונש",
        "penalties": "עונשים",
        "player": "שחקן",
        "players": "שחקנים",
        "poles": "מוטות",
        "practice": "אימון",
        "practices": "אימונים",
        "pilates": "פילאטיס",
        "ping pong": "פינג פונג",
        "race": "מרוץ",
        "races": "מרוצים",
        "racer": "מתחרה",
        "racers": "מתחרים",
        "racing": "מרוץ",
        "referee": "שופט",
        "referees": "שופטים",
        "rink": "זירה",
        "rinks": "זירות",
        "rival": "יריב",
        "rivals": "יריבים",
        "rower": "חותר",
        "rowers": "חותרים",
        "rowing": "לחתור",
        "rugby": "רוגבי",
        "runner": "רץ",
        "runners": "רצים",
        "running": "ריצה",
        "sailing": "מפליג",
        "score": "ציון",
        "scores": "ציונים",
        "scorer": "מבקיע",
        "scorers": "מבקיעים",
        "skate": "החלקה",
        "skates": "מחליקים",
        "skateboard": "סקייטבורד",
        "skateboards": "סקייטבורדים",
        "skateboarding": "סקייטבורד",
        "skater": "מחליק",
        "skaters": "מחליקים",
        "ski": "סקי",
        "skis": "מגלשיים",
        "skier": "גולש סקי",
        "skiers": "גולשי סקי",
        "skiing": "גלישת סקי",
        "snowboard": "סנובורד",
        "snowboards": "סנובורדים",
        "snowboarder": "גולש סנובורד",
        "snowboarders": "גולשי סנובורד",
        "snowboarding": "גלישת סנובורד",
        "snorkeling": "שנורקלינג",
        "soccer": "כדורגל",
        "spectator": "צופה",
        "spectators": "צופים",
        "sport": "ספורט",
        "sports": "ספורט",
        "sportsman": "ספורטאי",
        "sportsmen": "ספורטאים",
        "sportswoman": "ספורטאית",
        "sportswomen": "ספורטאיות",
        "sprint": "ספרינט",
        "stadium": "אצטדיון",
        "stadiums": "אצטדיונים",
        "stick": "מקל",
        "sticks": "מקלות",
        "strike": "להכות",
        "strikes": "מכה",
        "surf": "גלישה",
        "surfer": "גולש",
        "surfers": "גולשים",
        "sumo": "סומו",
        "surfing": "לגלוש",
        "swim": "שחייה",
        "swims": "שחיות",
        "swimmer": "שחיין",
        "swimmers": "שחיינים",
        "swimming": "לשחות",
        "table tennis": "טניס שולחן",
        "taekwondo": "טקוואנדו",
        "target": "מטרה",
        "targets": "מטרות",
        "team": "קבוצה",
        "teams": "קבוצות",
        "tennis": "טניס",
        "throw": "זריקה",
        "throws": "זריקות",
        "thrower": "זורק",
        "throwers": "זורקים",
        "track": "מסלול",
        "trainer": "מאמן",
        "trainers": "מאמנים",
        "triathlon": "טריאתלון",
        "trophy": "גביע",
        "trophies": "גביעים",
        "umpire": "שופט",
        "umpires": "שופטים",
        "uniform": "מדים",
        "uniforms": "מדים",
        "victory": "ניצחון",
        "victories": "ניצחונות",
        "volleyball": "כדורעף",
        "walker": "הליכון",
        "walkers": "הליכונים",
        "walking": "ללכת",
        "weight": "משקל",
        "weights": "משקולות",
        "weightlifter": "מרים משקולות",
        "weightlifters": "מרימי משקולות",
        "weightlifting": "הרמת משקולות",
        "win": "לנצח",
        "wins": "ניצחונות",
        "winner": "זוכה",
        "winners": "זוכים",
        "winning": "לנצח",
        "winnings": "זכיות",
        "wrestler": "מתאבק",
        "wrestlers": "מתאבקים",
        "wrestling": "היאבקות",
        "yoga": "יוגה",
        "zumba": "זומבה"
    },

    "Emotions_hebrew": {
    'abandoned': 'נטוש',
    'acrimonious': 'חריף',
    'addicted': 'מכור',
    'addicting': 'ממכר',
    'addiction': 'התמכרות',
    'addict': 'מכור',
    'adoring': 'להעריץ',
    'adore': 'מעריץ',
    'affectionate': 'חיבה',
    'afraid': 'מפחד',
    'aggrieved': 'נפגע',
    'agitated': 'נסער',
    'agonized': 'מיוסר',
    'agony': 'יגון',
    'alarmed': 'מודאג',
    'alienated': 'מנוכר',
    'aloof': 'מרוחק',
    'amazed': 'מופתע',
    'ambivalent': 'אמביוולנטי',
    'amorous': 'אוהב',
    'amused': 'משועשע',
    'angry': 'כועס',
    'anger': 'כעס',
    'anguished': 'מיוסר',
    'annoyed': 'מוטרד',
    'annoying': 'מעצבן',
    'anxious': 'חרד',
    'apathetic': 'אדיש',
    'appalled': 'מזועזע',
    'appreciated': 'מוערך',
    'apprehensive': 'חושש',
    'ardent': 'נלהב',
    'ashamed': 'מתבייש',
    'astonished': 'נדהם',
    'attracted': 'נמשך',
    'awed': 'ירא',
    'awe-struck': 'נפעם',
    'awkward': 'מביך',
    'awkwardness': 'מבוכה',
    'bashful': 'מבויש',
    'bemused': 'נבוך',
    'bereaved': 'שכול',
    'betrayed': 'נבגד',
    'bewildered': 'מבולבל',
    'bitter': 'מר',
    'blissful': 'מאושר',
    'boastful': 'מתרברב',
    'bored': 'משועמם',
    'boring': 'משעמם',
    'brave': 'אמיץ',
    'broken heart': 'לב שבור',
    'broken hearted': 'שבור לב',
    'calm': 'רגוע',
    'cantankerous': 'עצבני',
    'captivated': 'שבוי',
    'caring': 'אכפתי',
    'cautious': 'זהיר',
    'cheerful': 'עליז',
    'cherished': 'אהוב',
    'claustrophobic': 'קלסטרופובי',
    'clingy': 'נזקק',
    'comfortable': 'נוח',
    'compassionate': 'רחום',
    'complacent': 'שאנן',
    'confident': 'בטוח',
    'conflicted': 'מתלבט',
    'confused': 'מבולבל',
    'confusing': 'מבלבל',
    'contemplative': 'מהרהר',
    'contemptuous': 'בוז',
    'contrite': 'חרטתי',
    'courageous': 'אמיץ',
    'cowardly': 'פחדני',
    'cranky': 'עצבני',
    'craving': 'משתוקק',
    'curious': 'סקרן',
    'cynical': 'ציני',
    'defiant': 'מתריס',
    'dejected': 'מדוכא',
    'delighted': 'מרוצה',
    'demoralized': 'מדוכא',
    'dependent': 'תלוי',
    'depressed': 'מדוכא',
    'depression': 'דיכאון',
    'deserted': 'נטוש',
    'desirous': 'רוצה',
    'desire': 'תשוקה',
    'despair': 'ייאוש',
    'despairing': 'מיואש',
    'desperate': 'נואש',
    'desperation': 'ייאוש',
    'determined': 'נחוש',
    'devastated': 'הרוס',
    'devastating': 'הרסני',
    'disappointed': 'מאוכזב',
    'disappointing': 'מאכזב',
    'discontented': 'לא מרוצה',
    'discouraged': 'מיואש',
    'disgruntled': 'ממורמר',
    'disgust': 'גועל',
    'disgusted': 'נגעל',
    'disillusioned': 'מאוכזב',
    'dismayed': 'מבועת',
    'disoriented': 'מבולבל',
    'disparaged': 'מושפל',
    'distracted': 'מוסח',
    'distressed': 'מודאג',
    'distraught': 'נסער',
    'disturbed': 'מוטרד',
    'doubt': 'ספק',
    'doubts': 'ספקות',
    'doubtful': 'ספקני',
    'downtrodden': 'מדוכא',
    'dreamy': 'חולמני',
    'dubious': 'מפוקפק',
    'eager': 'להוט',
    'ecstatic': 'נלהב',
    'elated': 'מרומם',
    'embarrassed': 'נבוך',
    'emboldened': 'מעודד',
    'emotion': 'רגש',
    'emotions': 'רגשות',
    'emotional': 'רגשי',
    'empathetic': 'אמפתי',
    'enchanted': 'מוקסם',
    'encouraged': 'מעודד',
    'energized': 'נמרץ',
    'energetic': 'אנרגטי',
    'engrossed': 'שקוע',
    'enraged': 'זועם',
    'enthusiastic': 'נלהב',
    'enthralled': 'מהופנט',
    'envious': 'קנאי',
    'euphoric': 'אופורי',
    'exasperated': 'ממורמר',
    'excited': 'נרגש',
    'excluded': 'מודר',
    'exhausted': 'מותש',
    'exhilarated': 'מרומם',
    'exploited': 'מנוצל',
    'fatigued': 'עייף',
    'fearful': 'מפוחד',
    'fearless': 'חסר פחד',
    'feeling': 'הרגשה',
    'feelings': 'רגשות',
    'feel': 'להרגיש',
    'flustered': 'מבולבל',
    'forlorn': 'נטוש',
    'fortunate': 'בר מזל',
    'frantic': 'מטורף',
    'frightened': 'מפוחד',
    'frustrated': 'מתוסכל',
    'fulfilled': 'מוגשם',
    'furious': 'זועם',
    'giddy': 'סחרחורת',
    'gleeful': 'עליז',
    'gloomy': 'קודר',
    'gracefull': 'חינני',
    'gracefully': 'בחן',
    'grateful': 'אסיר תודה',
    'greedy': 'חמדן',
    'grief_stricken': 'שבור לב',
    'grumpy': 'זעפן',
    'guilt': 'אשמה',
    'guilty': 'אשם',
    'happiness': 'אושר',
    'harassed': 'מוטרף',
    'hate': 'שנאה',
    'hateful': 'שונא',
    'hated': 'שנוא',
    'heartbroken': 'שבור לב',
    'helpless': 'חסר אונים',
    'hesitant': 'מהסס',
    'hopeful': 'מלא תקווה',
    'hopefully': 'בתקווה',
    'exposed': 'חשוף',
    'exuberant': 'נלהב',
    'fascinated': 'מוקסם',
    'hopeless': 'חסר תקווה',
    'horrified': 'מזועזע',
    'hostile': 'עויין',
    'humiliated': 'מושפל',
    'humorous': 'מצחיק',
    'hungry': 'רעב',
    'hunger': 'רעב',
    'hurt': 'פגוע',
    'hurting': 'כואב',
    'hysterical': 'היסטרי',
    'hysteria': 'היסטריה',
    'impatient': 'חסר סבלנות',
    'in love with': 'מאוהב ב',
    'fall in love': 'להתאהב',
    'fell in love': 'התאהב',
    'falling in love': 'להתאהב',
    'indignant': 'ממורמר',
    'indifferent': 'אדיש',
    'inferior': 'נחות',
    'infatuated': 'מאוהב',
    'insane': 'מטורף',
    'insecure': 'חסר ביטחון',
    'insignificant': 'חסר משמעות',
    'insulted': 'נעלב',
    'intimidated': 'מאוים',
    'intrigued': 'מסוקרן',
    'loving': 'אוהב',
    'melancholic': 'מלנכולי',
    'meltdown': 'התמוטטות',
    'irritated': 'מוטרד',
    'isolated': 'מבודד',
    'jealous': 'קנאי',
    'jealously': 'בקנאה',
    'jittery': 'עצבני',
    'joyful': 'שמח',
    'jovial': 'עליז',
    'jubilant': 'צוהל',
    'kind': 'אדיב',
    'languid': 'רפוי',
    'lazy': 'עצלן',
    'lethargic': 'אדיש',
    'liberated': 'משוחרר',
    'lively': 'מלא חיים',
    'loathing': 'תיעוב',
    'lonely': 'בודד',
    'loneliness': 'בדידות',
    'longful': 'כמיהה',
    'lost': 'אבוד',
    'love': 'אהבה',
    'loved': 'אהוב',
    'merciful': 'רחום',
    'merry': 'עליז',
    'mindful': 'מודע',
    'miserable': 'אומלל',
    'mistrustful': 'חשדן',
    'moody': 'מצוברח',
    'mortified': 'מבועת',
    'mournful': 'אבל',
    'mystified': 'מבולבל',
    'mysterious': 'מסתורי',
    'nervous': 'עצבני',
    'nostalgic': 'נוסטלגי',
    'numb': 'קהה',
    'obsessed': 'אובססיבי',
    'offended': 'נעלב',
    'open-hearted': 'פתוח לב',
    'optimistic': 'אופטימי',
    'outraged': 'זועם',
    'overjoyed': 'מאושר',
    'overwhelmed': 'המום',
    'pacified': 'מפויס',
    'panicked': 'נבהל',
    'panicky': 'בפאניקה',
    'paranoid': 'פרנואיד',
    'passionate': 'נלהב',
    'patient': 'סבלני',
    'patiently': 'בסבלנות',
    'peaceful': 'שליו',
    'pensive': 'מהורהר',
    'perplexed': 'מבולבל',
    'persecuted': 'נרדף',
    'pessimistic': 'פסימי',
    'petrified': 'מאובן',
    'pining': 'מתגעגע',
    'pitying': 'מרחם',
    'playful': 'שובב',
    'pleased': 'מרוצה',
    'prideful': 'יהיר',
    'privileged': 'חסוי',
    'proud': 'גאה',
    'protective': 'מגונן',
    'puzzled': 'מבולבל',
    'quiet': 'שקט',
    'rage': 'זעם',
    'rapturous': 'משולהב',
    'reassured': 'הרגיע',
    'rebellious': 'מרדן',
    'regretful': 'מתחרט',
    'rejected': 'דחוי',
    'relaxed': 'רגוע',
    'relieved': 'מוקל',
    'reluctant': 'מהסס',
    'remorseful': 'מלא חרטה',
    'resentful': 'נוטר טינה',
    'resigned': 'מוותר',
    'respected': 'מכובד',
    'restless': 'חסר מנוחה',
    'revulsed': 'מתועב',
    'ridiculous': 'מגוחך',
    'romantic': 'רומנטי',
    'sad': 'עצוב',
    'sadness': 'עצב',
    'sane': 'שפוי',
    'saner': 'שפוי יותר',
    'safe': 'בטוח',
    'satisfied': 'מסופק',
    'scared': 'מפוחד',
    'scary': 'מפחיד',
    'scornful': 'בוז',
    'secure': 'בטוח',
    'self-conscious': 'מודע לעצמו',
    'self conscious': 'מודע לעצמו',
    'sentimental': 'רגשני',
    'serene': 'שלו',
    'sexy': 'סקסי',
    'sexier': 'יותר סקסי',
    'sensual': 'חושני',
    'shaken': 'רועד',
    'shame': 'בושה',
    'shameful': 'מבייש',
    'shameless': 'חסר בושה',
    'sick': 'חולה',
    'shocked': 'המום',
    'shy': 'ביישן',
    'skeptic': 'סקפטי',
    'skeptical': 'ספקני',
    'skepticism': 'ספקנות',
    'sleepy': 'מנומנם',
    'smug': 'שחצן',
    'sorrow': 'יגון',
    'sorrowful': 'עָצוּב',
    'spiteful': 'נקמני',
    'startled': 'נבהל',
    'stern': 'קפדן',
    'stressed': 'לחוץ',
    'stressfull': 'מלא לחץ',
    'stressfully': 'בלחץ',
    'strong': 'חזק',
    'stunned': 'המום',
    'stupefied': 'נדהם',
    'successful': 'מצליח',
    'sullen': 'קודר',
    'surprised': 'מופתע',
    'suspicious': 'חשדן',
    'sympathetic': 'אמפתי',
    'tearful': 'דומע',
    'tenacious': 'עקשן',
    'tender': 'עדין',
    'tense': 'מתוח',
    'tentative': 'מהוסס',
    'terrified': 'מבוהל',
    'thankful': 'מלא תודה',
    'thoughtful': 'מהורהר',
    'threatened': 'מאוים',
    'thrilled': 'נרגש מאוד',
    'timid': 'חששן',
    'tired': 'עייף',
    'tired of': 'נמאס',
    'tiredness': 'עייפות',
    'touched': 'נרגש',
    'tranquil': 'שליו',
    'triumphant': 'מנצח',
    'troubled': 'מודאג',
    'trust': 'אמון',
    'trusting': 'בוטח',
    'uncomfortable': 'לא נוח',
    'unconfident': 'חסר ביטחון',
    'unfulfilled': 'לא התממש',
    'unhappy': 'לא שמח',
    'unnerved': 'מוטרד',
    'unsettled': 'לא יציב',
    'unstable': 'בלתי יציב',
    'uplifted': 'מרומם',
    'upset': 'נסער',
    'valued': 'נערך',
    'vengeful': 'נקמני',
    'vigilant': 'דרוך',
    'weary': 'יגע',
    'wistful': 'נוגה',
    'withdrawn': 'נסוג',
    'woeful': 'אומלל',
    'worried': 'מודאג',
    'worthless': 'חסר ערך',
    'wounded': 'פצוע',
    'wrathful': 'זועם',
    'vindicated': 'מוצדק',
    'vulnerable': 'פגיע',
    'wary': 'זהיר',
    'yearning': 'כמיהה',
    'zestful': 'נלהב'
    },

    "intended_hebrew" : {
    'mother': 'אמא',
    'mothers': 'אמהות',
    'father': 'אבא',
    'fathers': 'אבות',
    'mom': 'אמא',
    'dad': 'אבא',
    'mommy': 'אמא',
    'daddy': 'אבא',
    'mum': 'אמא',
    'mumsy': 'אמהית',
    'papa': 'אבא',
    'mama': 'אמא',
    'parent': 'הורה',
    'parents': 'הורים',
    'stepmother': 'אמא חורגת',
    'stepfather': 'אבא חורג',
    'stepparent': 'הורה חורג',
    'stepmom': 'אמא חורגת',
    'stepdad': 'אבא חורג',
    'grandmother': 'סבתא',
    'grandmothers': 'סבתות',
    'grandfather': 'סבא',
    'grandfathers': 'סבים',
    'grandma': 'סבתא',
    'grandpa': 'סבא',
    'granny': 'סבתא',
    'grandparent': 'סבא או סבתא',
    'grandparents': 'סבא וסבתא',
    'greatgrandmother': 'סבתא רבא',
    'greatgrandfather': 'סבא רבא',
    'greatgrandparents': 'סבא וסבתא רבא',
    'sister': 'אחות',
    'sisters': 'אחיות',
    'brother': 'אח',
    'brothers': 'אחים',
    'siblings': 'אחים',
    'stepsister': 'אחות חורגת',
    'stepsisters': 'אחיות חורגות',
    'stepbrother': 'אח חורג',
    'stepbrothers': 'אחים חורגים',
    'halfsister': 'אחות למחצה',
    'halfbrother': 'אח למחצה',
    'twin': 'תאום',
    'twins': 'תאומים',
    'son': 'בן',
    'daughter': 'בת',
    'daughters': 'בנות',
    'child': 'ילד',
    'children': 'ילדים',
    'stepson': 'בן חורג',
    'stepdaughter': 'בת חורגת',
    'grandson': 'נכד',
    'granddaughter': 'נכדה',
    'greatgrandson': 'נין',
    'great-grandson': 'נין',
    'greatgranddaughter': 'נינה',
    'great-granddaughter': 'נינה',
    'uncle': 'דוד',
    'aunt': 'דודה',
    'auntie': 'דודה',
    'nephew': 'אחיין',
    'niece': 'אחיינית',
    'greatuncle': 'דוד רבא',
    'greataunt': 'דודה רבא',
    'cousin': 'בן דוד',
    'husband': 'בעל',
    'housewife': 'עקרת בית',
    'wife': 'אישה',
    'spouse': 'בן זוג',
    'partner': 'שותף',
    'life partner': 'בן/בת זוג לחיים',
    'soulmate': 'נפש תאומה',
    'in-law': 'חמי',
    'mother-in-law': 'חמות',
    'father-in-law': 'חותן',
    'brother-in-law': 'גיס',
    'sister-in-law': 'גיסה',
    'son-in-law': 'חתן',
    'daughter-in-law': 'כלה',
    'family': 'משפחה',
    'families': 'משפחות',
    'relatives': 'קרובי משפחה',
    'kin': 'קרובי משפחה',
    'next of kin': 'קרוב משפחה',
    'descendant': 'צאצא',
    'ancestor': 'אב קדמון',
    'lineage': 'שושלת',
    'heritage': 'מורשת',
    'household': 'משק בית',
    'clan': 'שבט',
    'tribe': 'שבט',
    'dynasty': 'שושלת',
    'bloodline': 'שושלת דם',
    'marriage': 'נישואין',
    'wedding': 'חתונה',
    'weddings': 'חתונות',
    'anniversary': 'יום נישואין',
    'adoption': 'אימוץ',
    'adopted': 'מאומץ',
    'adopting': 'מאמץ',
    'foster family': 'משפחת אומנה',
    'foster child': 'ילד אומנה',
    'foster parent': 'הורה אומנה',
    'godmother': 'סנדקית',
    'godfather': 'סנדק',
    'godparents': 'סנדקים',
    'godchild': 'ילד סנדקות',
    'godson': 'סנדק בן',
    'goddaughter': 'סנדקית בת',
    'guardian': 'אפוטרופוס',
    'caretaker': 'מטפל',
    'home': 'בית',
    'house': 'בית',
    'houses': 'בתים',
    'domestic': 'ביתי',
    'nuclear family': 'משפחה גרעינית',
    'extended family': 'משפחה מורחבת',
    'blended family': 'משפחה מעורבת',
    'single parent': 'הורה יחיד',
    'single father': 'אב חד הורי',
    'single mother': 'אם חד הורית',
    'breadwinner': 'מפרנס',
    'caregiver': 'מטפל עיקרי',
    'sibling rivalry': 'יריבות בין אחים',
    'family reunion': 'מפגש משפחתי',
    'family tree': 'עץ משפחה',
    'family name': 'שם משפחה',
    'maiden name': 'שם נעורים',
    'surname': 'שם משפחה',
    'last name': 'שם משפחה',
    'first name': 'שם פרטי',
    'nickname': 'כינוי',
    'given name': 'שם פרטי',
    'middle name': 'שם אמצעי',
    'divorce': 'גירושין',
    'remarriage': 'נישואין מחדש',
    'co-parenting': 'הורות משותפת',
    'custody': 'משמורת',
    'joint custody': 'משמורת משותפת',
    'shared custody': 'משמורת משותפת',
    'infant': 'תינוק',
    'toddler': 'פעוט',
    'teenager': 'מתבגר',
    'adolescent': 'נוער',
    'adult': 'מבוגר',
    'elder': 'זקן',
    'senior': 'אזרח ותיק',
    'newborn': 'יילוד',
    'baby': 'תינוק',
    'childhood': 'ילדות',
    'adulthood': 'בגרות',
    'generation': 'דור',
    'heir': 'יורש',
    'heiress': 'יורשת',
    'successor': 'יורש',
    'progeny': 'צאצאים',
    'offspring': 'צאצא',
    'family bond': 'קשר משפחתי',
    'family support': 'תמיכה משפחתית',
    'discipline': 'משמעת',
    'tradition': 'מסורת',
    'roots': 'שורשים',
    'homecoming': 'שיבה הביתה',
    'mother figure': 'דמות אם',
    'father figure': 'דמות אב',
    'blood relative': 'קרוב משפחה',
    'biological parent': 'הורה ביולוגי',
    'biological child': 'ילד ביולוגי',
    'chosen family': 'משפחה נבחרת',
    'surrogate mother': 'אם פונדקאית',
    'adoptive parent': 'הורה מאמץ',
    'family friend': 'חבר משפחה',
    'household member': 'חבר משק בית',
    'family unit': 'יחידת משפחה',
    'kinship': 'קשר משפחתי',
    'family dinner': 'ארוחת ערב משפחתית',
    'family outing': 'טיול משפחתי',
    'family photo': 'תמונה משפחתית',
    'family values': 'ערכי משפחה',
    'family love': 'אהבת משפחה',
    'family issues': 'בעיות משפחתיות',
    'family drama': 'דרמה משפחתית',
    'family gathering': 'התכנסות משפחתית',
    'family holiday': 'חופשה משפחתית',
    'family tradition': 'מסורת משפחתית',
    'family structure': 'מבנה משפחתי',
    'family member': 'בן משפחה',
    'family connection': 'קשר משפחתי'
    }

}