# Define categories and associated words
categories = {
    "Animals": [
        "animal", "animals", "alligator", "alligators", "alpaca", "alpacas", "anaconda", "anacondas", "ant", "ants", "antelope", "antelopes", "armadillo", "armadillos", "baboon", "baboons", "bat", "bats", "bear", "bears",
        "beast", "bee", "bees", "beetle", "beetles", "buffalo", "buffalos", "butterfly", "butterflies", "camel", "camels",
        "cat", "cats", "caterpillar", "caterpillars", "cheetah", "cheetahs", "chicken", "chickens", "chimpanzee", "chimpanzees", "chinchilla", "chinchillas", "chipmunk",
        "cow", "cows", "cobra", "cobras", "crab", "crabs", "cricket", "crickets", "crocodile", "crocodiles", "crow", "crows", "deer", "dog", "dogs", "dolphin", "dolphins",
        "donkey", "donkeys", "dove", "doves", "dragon", "dragonfly", "dragonflies", "duck", "ducks", "dinosaur", "dinosaurs", "eagle", "eagles", "elephant", "elephants", "falcon", "falcons", "ferret", "ferrets",
        "fish", "firefly", "fireflies", "flamingo", "flamingos", "fox", "foxes", "frog", "frogs", "giraffe", "giraffes", "goat", "goats",
        "goose", "geese", "gorilla", "gorillas", "goldfish", "grasshopper", "grasshoppers", "grizzly", "hamster", "hamsters", "hawk", "hawks", "hedgehog", "hedgehogs",
        "hippo", "hippos", "hippopotamus", "horse", "horses", "hyena", "hyenas", "ibex", "ibexes", "iguana", "iguanas", "jaguar", "jaguars", "jellyfish", "kangaroo", "kangaroos", "koala", "koalas",
        "leopard", "leopards", "lemur", "lemurs", "lice", "lion", "lions", "lizard", "lizards", "lobster", "lobsters", "llama", "llamas", "mole", "moles", "monkey", "monkeys", "mongoose", "mongooses",
        "mosquito", "mosquitoes", "moth", "mouse", "mice", "nightingale", "nightingales", "octopus", "octopuses", "ostrich", "ostriches", "otter", "otters", "owl", "owls",
        "ox", "oxen", "panda", "pandas", "parrot", "parrots", "peacock", "peacocks", "pelican", "pelicans", "penguin", "penguins", "pig", "pigs",
        "pigeon", "pigeons", "Penguin", "Penguins", "platypus", "platypuses", "porcupine", "porcupines", "puppy", "rabbit", "rabbits", "raccoon", "raccoons", "rat", "rats", "raven", "ravens",
        "reindeer", "rhino", "rhinos", "scorpion", "scorpions", "sea_lion", "sea_lions", "seal", "seals", "seahorse", "seahorses", "sea_urchin", "sea_urchins",  "seagull", "seagulls", "shark", "sharks", "sheep", "skunk", "skunks", "sloth", "sloths",
        "snail", "snails", "snake", "snakey", "snakes", "songbird", "songbirds", "sparrow", "sparrows", "spider", "spiders", "squid", "squids", "squirrel", "squirrels", "starfish", "stingray", "stingrays",
        "swan", "swans", "swordfish", "termite", "termites", "tiger", "tigers", "toad", "toads", "toucan", "toucans", "turtle", "turtles", "unicorn", "unicorns", "walrus", "walruses",
        "wasp", "wasps", "whale", "whales", "wolf", "wolves", "zebra", "zebras"
    ],

    "Clothing": [
        "backpack", "backpacks", "belt", "belts", "beanie", "beanies", "blazer", "blazers", "blouse", "blouses",
        "boots", "bra", "bras", "briefs", "cape", "capes", "cardigan", "cardigans", "coat", "coats",
        "corset", "corsets", "cufflinks", "dress", "dresses", "earrings", "espadrilles", "flip-flops",
        "gown", "gowns", "glasses", "glove", "gloves", "hat", "hats", "handbag", "handbags","heel", "heels", "helmet", "helmets", "hoodie", "hoodies",
        "jacket", "jackets", "jeans", "jumpsuit", "jumpsuits", "kimono", "kimonos", "leggings", "mask", "masks", "mittens", "necklace", "necklaces",
        "overall", "overalls", "overcoat", "overcoats", "pants", "pajama", "pajamas", "panties", "poncho", "ponchos", "purse", "purses", "raincoat", "raincoats",
        "ring", "rings", "robe", "robes", "sandal", "sandals", "satchel", "satchels", "scarf", "scarves", "shirt", "shirts",
        "shoe", "shoes", "shorts", "skirt", "skirts", "slipper", "slippers", "sleepwear", "sneaker", "sneakers", "socks", "suit", "suits", "sunglasses", "sweater", "sweaters",
        "t-shirt", "t-shirts", "tank_top", "tank_tops", "thobe", "tie", "ties", "tights", "tracksuit", "tracksuits", "tunic", "tunics",
        "turban", "turbans", "tuxedo", "tuxedos", "uniform", "uniforms", "veil", "veils", "vest", "vests", "wallet", "wallets", "watch", "watches", "windbreaker", "windbreakers",
        "wristband", "wristbands"
    ],

    "Food": [
        "almond", "almonds", "apple", "apples", "avocado", "avocados", "artichoke", "asparagus", "bacon", "banana", "bananas", "bagel", "baguette", "barley", "basil", "beans", "beef", "blackberry", "blackberries", "blueberry", "blueberries", "bread", "broccoli", "burger", "burgers",
        "butter", "cabbage", "cake", "cakes", "candy", "candies", "carrot", "carrots", "caramel", "cashew", "cashews", "cauliflower", "cereal", "cherry", "cherries", "cheese", "chips", "chickpea",
        "chocolate", "cinnamon", "coconut", "coconuts", "coffee", "cookie", "cookies", "corn", "cracker", "crackers", "crepe", "croissant", "cucumber", "cucumbers", "donut", "donuts",
        "egg", "eggs", "eggplant", "eggplants", "fish", "fries", "garlic", "ginger", "grape", "grapes", "grapefruit", "ham", "hamburger", "hamburgers", "hazelnut", "hazelnuts", "honey", "hotdog", "hotdogs","ice",
        "ice_cream", "jam", "jelly", "juice", "ketchup", "kebab", "kiwi", "kiwis", "lasagna", "lentil", "licorice", "lemon", "lemons", "lettuce", "lime", "lobster", "lobsters", "macadamia", "macaroni", "macaron", "mayonnaise", "meatball", "mint", "mango", "mangos", "mangoes",
        "meat", "melon", "melons", "milk", "mousse", "muffin", "muffins", "mushroom", "mushrooms", "mustard", "noodle", "noodles", "nut", "nuts", "oat", "oats", "okra", "oregano", "oyster", "oatmeal", "olive", "olives",
        "onion", "onions", "orange", "oranges", "pancake", "pancakes", "pasta", "pastry", "peach", "peaches", "peanut", "peanuts", "pear", "pears", "peas", "pepper", "peppers", "pecan", "pesto", "pickle", "pistachio",
        "pie", "pies", "pineapple", "pineapples", "pizza", "plum", "plums", "pork", "popcorn", "potato", "potatoes", "pumpkin", "pretzel", "pretzels", "raisin", "raisins", "raspberry", "raspberries",
        "rice", "salad", "salmon", "sandwich", "sandwiches", "sausage", "sausages", "shrimp", "smoothie", "snack", "snacks", "soda", "soup", "spinach", "steak", "strawberry",
        "strawberries", "sugar", "syrup", "sushi", "sweet_potato", "taco", "tahini", "tea", "tomato", "tomatoes", "tofu", "tuna", "turkey", "tiramisu", "tortilla", "vinegar", "waffle", "waffles", "walnut", "walnuts", "water", "watermelon", "watermelons", "whipped_cream", "yogurt", "Yolk", "Zucchini"
    ],

    "Emotions": [
        "abandoned", "acrimonious", "addicted", "addicting", "addiction", "addict", "adoring", 
        "adore", "affectionate", "afraid", "aggrieved", "agitated", "agonized", "agony", 
        "alarmed", "alienated", "aloof", "amazed", "ambivalent", "amorous", "amused", "angry", 
        "anger", "anguished", "annoyed", "annoying", "anxious", "apathetic", "appalled", 
        "appreciated", "apprehensive", "ardent", "ashamed", "astonished", "attracted", "awed", 
        "awe-struck", "awkward", "awkwardness", "bashful", "bemused", "bereaved", "betrayed", 
        "bewildered", "bitter", "blissful", "boastful", "bored", "boring", "brave", "broken_heart", 
        "broken_hearted", "calm", "cantankerous", "captivated", "caring", "cautious", "cheerful", 
        "cherished", "claustrophobic", "clingy", "comfortable", "compassionate", "complacent", 
        "confident", "conflicted", "confused", "confusing", "contemplative", "contemptuous", 
        "contrite", "courageous", "cowardly", "cranky", "craving", "curious", "cynical", 
        "defiant", "dejected", "delighted", "demoralized", "dependent", 
        "depressed", "depression", "deserted", "desirous", "desire", "despair", "despairing", "desperate", "desperation", "determined", 
        "devastated", "devastating", "disappointed", "disappointing", "discontented", "discouraged", "disgruntled", "disgust", 
        "disgusted", "disillusioned", "dismayed", "disoriented", "disparaged", "distracted", "distressed", "distraught", "disturbed", 
        "doubt", "doubts", "doubtful", "downtrodden", "dreamy", "dubious", "eager", "ecstatic", "elated", "embarrassed", "emboldened", "emotion", "emotions", "emotional", 
        "empathetic", "enchanted", "encouraged", "energized", "energetic", "engrossed", "enraged", "enthusiastic", "enthralled", "envious", 
        "euphoric", "exasperated", "excited", "excluded", "exhausted", "exhilarated", "exploited", 
        "fatigued", "fearful", "fearless", "feeling", "feelings" "feel", "flustered", "forlorn", "fortunate", "frantic", "frightened", "frustrated", 
        "fulfilled", "furious", "giddy", "gleeful", "gloomy", "gracefull", "gracefully", "grateful", "greedy", "grief_stricken", "grumpy", 
        "guilt", "guilty", "happiness", "harassed", "hate", "hateful", "hated", "heartbroken", "helpless", 
        "hesitant", "hopeful", "hopefully", "exposed", "exuberant", "fascinated", 
        "hopeless", "horrified", "hostile", "humiliated", "humorous", "hungry", "hunger", 
        "hurt", "hurting", "hysterical", "hysteria", "impatient", "in_love_with", "fall_in_love", "fell_in_love", "falling_in_love",
        "indignant", "indifferent", "inferior", "infatuated", "insane", "insecure", "insignificant", 
        "insulted", "intimidated", "intrigued", "loving", "melancholic", "meltdown", 
        "irritated", "isolated", "jealous", "jealously", "jittery", "joyful", "jovial", "jubilant", 
        "kind", "languid", "lazy", "lethargic", 
        "liberated", "lively", "loathing", "lonely", "loneliness", "longful", "lost", "love", "loved", 
        "merciful", "merry", "mindful", "miserable", "mistrustful", "moody", "mortified", "mournful", "mystified", "mysterious", "nervous", "nostalgic", 
        "numb", "obsessed", "offended", "open-hearted", "optimistic", "outraged", "overjoyed", "overwhelmed", "pacified", "panicked", 
        "panicky", "paranoid", "passionate", "patient", "patiently", "peaceful", "pensive", "perplexed", "persecuted", "pessimistic", 
        "petrified", "pining", "pitying", "playful", "pleased", "prideful", "privileged", "proud", "protective", "puzzled", "quiet", 
        "rage", "rapturous", "reassured", "rebellious", "regretful", "rejected", "relaxed", "relieved", "reluctant", "remorseful", 
        "resentful", "resigned", "respected", "restless", "revulsed", "ridiculous", "romantic", "sad", "sadness", "sane", "saner", "safe", "satisfied", 
        "scared", "scary", "scornful", "secure", "self-conscious", "self_conscious", "sentimental", "serene", "sexy", "sexier", "sensual", "shaken", "shame", "shameful", "shameless", "sick",
        "shocked", "shy", "skeptic", "skeptical", "skepticism", "sleepy", "smug", "sorrow", "sorrowful", "spiteful", "startled", "stern", "stressed", "stressfull", 
        "stressfully", "strong", "stunned", "stupefied", "successful", "sullen", "surprised", "suspicious", "sympathetic", "tearful", 
        "tenacious", "tender", "tense", "tentative", "terrified", "thankful", "thoughtful", "threatened", "thrilled", "timid", "tired", "tired_of",
        "tiredness", "touched", "tranquil", "triumphant", "troubled", "trust", "trusting", 
        "uncomfortable", "unconfident", "unfulfilled", "unhappy", 
        "unnerved", "unsettled", "unstable", "uplifted", "upset", "valued", "vengeful", "vigilant", 
        "weary", "wistful", "withdrawn", "woeful", "worried", "worthless", "wounded", "wrathful", 
        "vindicated", "vulnerable", "wary", "yearning", "zestful"
],

    "Body Parts": [
        "abdomen", "ankle", "ankles", "appendix", "arm", "arms", "artery", "arteries", "belly", 
        "belly_button", "bladder", "blood", "bone", "bones", "brain",
        "calf", "calves", "cartilage", "cheek", "cheeks", "chest", "chin", "ear", "ears", 
        "eardrum", "elbow", "elbows", "eye", "eyes","eyebrow", "eyebrows", "eyelash", "eyelashes", 
        "eyeball", "eyeballs", "finger", "fingers", "foot", "feet", "forehead", "gallbladder", 
        "genital", "genitals", "groin", "gums", "hand", "hands", "hair", "head", 
        "hips", "jaw", "kidney", "kidneys", "knee", "knees", "larynx", "leg", "legs", "ligament", 
        "lip", "lips", "liver", "lung", "lungs", "mouth", "muscle", "muscles", "nail", "nails", 
        "navel", "neck", "nerve", "nerves", "nostril", "nostrils", "ovary", "ovaries",
        "palms", "pancreas", "pelvis", "penis", "pupil", "retina", "rib", "ribs", "scalp", 
        "scrotum", "shoulder", "shoulders", "shin", "shins", "skin", "skull", "spine", "spleen", 
        "stomach", "teeth", "tendon", "thigh", "thighs", "throat", "thumb", "thumbs", "toe", 
        "toes", "tongue", "tonsils", "tooth", "trachea", "ureter", "urethra", "uterus", 
        "uvula", "vein", "veins", "vocal_cords", "waist", "wrist", "wrists"
    ] ,

    "Family": [
        "mother", "mothers", "father", "fathers", "mom", "dad", "mommy", "daddy", "mum", "mumsy",
        "papa", "mama", "parent", "parents", "stepmother", "stepfather", "stepparent", "stepmom", 
        "stepdad", "grandmother", "grandmothers", "grandfather", "grandfathers", "grandma", 
        "grandpa", "granny", "grandparent", "grandparents", "greatgrandmother", "greatgrandfather", 
        "greatgrandparents", "sister", "sisters", "brother", "brothers", "siblings", "stepsister", 
        "stepsisters", "stepbrother", "stepbrothers", "halfsister", "halfbrother", "twin", "twins", 
        "son", "daughter", "daughters", "child", "children", "stepson", "stepdaughter", 
        "grandson", "granddaughter","greatgrandson", "greatgranddaughter", "uncle", "aunt", 
        "auntie", "nephew", "niece", "greatuncle", "greataunt", "cousin", "husband","housewife","wife", "spouse", "partner", 
        "life_partner", "soulmate", "in-law", "mother-in-law", "father-in-law", "brother-in-law", 
        "sister-in-law", "son-in-law", "daughter-in-law", "family", "families", "relatives", 
        "kin", "next_of_kin", "descendant", "ancestor", "lineage", "heritage", "household", 
        "clan", "tribe", "dynasty", "bloodline", "marriage", "wedding", "weddings", "anniversary", 
        "adoption", "adopted", "adopting", "foster_family", "foster_child", "foster_parent",
        "godmother", "godfather", "godparents", "godchild", "godson", "goddaughter",
        "guardian", "caretaker", "home", "house", "houses", "household", "domestic", "nuclear_family",
        "extended_family", "blended_family", "single_parent", "single_father", "single_mother",
         "breadwinner", "caregiver",
        "sibling_rivalry", "family_reunion", "family_tree", "family_name", "maiden_name", "surname",
        "last_name", "first_name", "nickname", "given_name", "middle_name",
        "divorce", "remarriage", "co-parenting", "custody", "joint_custody", "shared_custody",
        "infant", "toddler", "teenager", "adolescent", "adult", "elder", "senior",
        "newborn", "baby", "childhood", "adulthood", "generation",
        "heir", "heiress", "successor", "progeny", "offspring", "family_bond", 
        "family_support", "discipline", "tradition", "roots", "homecoming",
        "mother_figure", "father_figure", "blood_relative",
        "biological_parent", "biological_child", "chosen_family", "surrogate_mother",
        "adoptive_parent", "family_friend", "household_member", "family_unit", "kinship",
        "family_dinner", "family_outing", "family_photo", "family_values", "family_love",
        "family_issues", "family_drama", "family_gathering", "family_holiday",
        "family_tradition", "family_structure", "family_member", "family_connection"
    ],

    "Transport": [
        "car", "cars", "bus", "buses", "train", "trains", "truck", "trucks", "van", "vans", "ambulance", "ambulances",
        "taxi", "taxis", "motorcycle", "motorcycles", "bike", "bikes", "bicycle", "bicycles",
        "scooter", "scooters", "skateboard", "skateboards", "subway", "subways",
        "tram", "trams", "metro", "metros", "ferry", "ferries", "boat", "boats",
        "ship", "ships", "yacht", "yachts", "canoe", "canoes", "kayak", "kayaks",
        "helicopter", "helicopters", "plane", "planes", "airplane", "airplanes",
        "jet", "jets", "glider", "gliders", "spaceship", "spaceships", "rocket", "rockets",
        "hovercraft", "hovercrafts", "minivan", "minivans", "pickup", "pickups",
        "suv", "suvs", "lorry", "lorries", "trolley", "trolleys", "rickshaw", "rickshaws",
        "wagon", "wagons", "caravan", "caravans", "camper", "campers", "motorhome", "motorhomes",
        "taxicab", "taxicabs", "sailboat", "sailboats", "container_ship", "container_ships",
        "cargo_ship", "cargo_ships", "freight_train", "freight_trains", "bullet_train", "bullet_trains",
        "electric_car", "electric_cars", "hybrid_car", "hybrid_cars", "self-driving_car", "self-driving_cars",
        "electric_scooter", "electric_scooters", "electric_bike", "electric_bikes", "sail",
        "drive", "driver", "drivers", "passenger", "passengers", "pilot", "pilots", "mechanic", "mechanics",
        "chauffeur", "chauffeurs", "navigator", "navigators",
        "station", "stations", "terminal", "terminals", "runway", "runways",
        "port", "ports", "harbor", "harbors", "garage", "garages", "highway", "highways",
        "road", "roads", "street", "streets", "lane", "lanes", "avenue", "avenues",
        "intersection", "intersections", "crosswalk", "crosswalks", "traffic_light", "traffic_lights",
        "stop_sign", "stop_signs", "roundabout", "roundabouts", "bridge", "bridges",
        "tunnel", "tunnels", "railway", "railways", "railroad", "railroads",
        "track", "tracks", "bike_lane", "bike_lanes", "flight", "flights",
        "boarding_pass", "boarding_passes", "ticket", "tickets", "fare", "fares",
        "transport", "transportation","delivery", "deliveries", "freight",
        "cargo", "shipment", "shipments", "commute", "commutes", "journey", "journeys", "landing",
        "takeoff", "takeoffs", "boarding", "trip", "trips", "travel", "travels", "transit", 
        "route", "routes", "itinerary", "itineraries", "departure", "departures", "arrival", 
        "arrivals", "delay", "delays", "schedule", "schedules"
    ],

    "Sports": [
    "archer", "archers", "archery", "athlete", "athletes", "badminton",
    "ball", "balls", "baseball", "baseballs", "bat", "bats",
    "basket", "baskets", "basketball", "basketballs", "biker", "bikers",
    "billiard", "billiards", "bleacher", "bleachers", "board", "boards",
    "boat", "boats", "bow", "bows", "bowler", "bowlers",
    "bowling", "boxer", "boxers", "boxing", "captain", "captains",
    "canoe", "canoes", "canoeing", "catcher", "catchers", "champion",
    "champions", "cheer", "cheerleader", "cheerleaders", "climber", "climbers",
    "climbing", "crossfit", "coach", "coaches", "competition", "competitions",
    "cricket", "crew", "crews", "cyclist", "cyclists", "cycling",
    "dart", "darts", "diver", "divers", "diving", "dodgeball",
    "equipment", "fencer", "fencers", "fencing", "field", "fields",
    "fighter", "fighters", "fishing", "football", "footballs","game", "games", "goal",
    "goals", "goalkeeper", "goalkeepers", "goggles", "golf", "golfs",
    "golfer", "golfers", "gym", "gyms", "gymnast", "gymnasts",
    "gymnastics", "helmet", "helmets", "hiker", "hikers", "hiking",
    "hockey", "horse", "horses", "ice_hockey", "ice_skating", "javelin",
    "javelins", "jogger", "joggers", "jogging", "judoka", "judokas",
    "judo", "jump", "jumps", "judge", "jiujitsu", "karate",
    "kayak", "kayaks", "kayaking", "kick", "kicks", "kicking",
    "kicker", "kickers", "kitesurfing", "lacrosse", "league", "leagues",
    "loser", "losers", "martial_art", "martial_arts", "match", "matches",
    "medal", "medals", "mountain_biking", "net", "nets", "olympics",
    "paddle", "paddles", "parachute", "parachutes", "paragliding", "parkour",
    "penalty", "penalties", "player", "players", "poles", "practice",
    "practices", "pilates", "ping_pong", "race", "races", "racer",
    "racers", "racing", "referee", "referees", "rink", "rinks",
    "rival", "rivals", "rower", "rowers", "rowing", "rugby",
    "runner", "runners", "running", "sailing", "score", "scores",
    "scorer", "scorers", "skate", "skates", "skateboard", "skateboards",
    "skateboarding", "skater", "skaters", "ski", "skis", "skier",
    "skiers", "skiing", "snowboard", "snowboards", "snowboarder", "snowboarders",
    "snowboarding", "snorkeling", "soccer", "spectator", "spectators", "speed_skating",
    "sport", "sports", "sportsman", "sportsmen", "sportswoman", "sportswomen",
    "sprint", "stadium", "stadiums", "stick", "sticks", "strike",
    "strikes", "surf", "surfs", "surfer", "surfers", "sumo",
    "surfing", "swim", "swims", "swimmer", "swimmers", "swimming",
    "table_tennis", "taekwondo", "target", "targets", "team", "teams",
    "tennis", "throw", "throws", "thrower", "throwers", "track",
    "trainer", "trainers", "triathlon", "trophy", "trophies", "umpire",
    "umpires", "uniform", "uniforms", "victory", "victories", "volleyball",
    "walker", "walkers", "walking", "weight", "weights", "weightlifter",
    "weightlifters", "weightlifting", "win", "wins", "winner", "winners",
    "winning", "winnings", "wrestler", "wrestlers", "wrestling", "yacht",
    "yachts", "yachting", "yoga", "zumba"
]

}

# Define multi-word keywords to preserve as single tokens
multi_word_keywords = [
    # Family Members category
    "blood relative", "biological parent", 
    "biological child", "chosen family", "family friend", "household member", 
    "family unit", "family bond", "family support", "family gathering", 
    "family holiday", "family tradition", "family love", "family issues", 
    "family drama", "family connection", "family member", "mother figure", 
    "father figure", "life partner", "next of kin", 
    "foster family", "foster child", "foster parent", "nuclear family", 
    "extended family", "blended family", "single parent", "single father", 
    "single mother", "sibling rivalry", "family reunion", "family tree", 
    "family name", "maiden name", "last name", "first name", "given name", 
    "middle name", "surrogate mother", "adoptive parent", "joint custody", "shared custody",
    "family dinner", "family outing", "family photo", "family values", "family structure",

    # other categories
    "ice cream", "sweet potato", "whipped cream", "tank top", "tank tops", "in love with", "fall in love", "fell in love", "falling in love",
    "belly button", "vocal cords", "broken hearted", "broken heart", 
    "sea lion", "sea lions", "sea urchin", "sea urchins", "self conscious", "tired of",

    # Transport category
    "container ship", "container ships", "cargo ship", "cargo ships",
    "freight train", "freight trains", "bullet train", "bullet trains",
    "electric car", "electric cars", "hybrid car", "hybrid cars",
    "self-driving car", "self-driving cars", "electric scooter", "electric scooters",
    "electric bike", "electric bikes", "bike lane", "bike lanes",
    "boarding pass", "boarding passes", "traffic light", "traffic lights",
    "stop sign", "stop signs",

    # Sports category
    "ping pong", "table tennis", "speed skating", "martial arts", "martial art", "ice skating", "ice hockey"
]


