intended_hebrew = {
    "Animals_hebrew": {
        "animal": "חיה",
        "animals": "חיות",
        "alligator": "תנין",
        "alligators": "תנינים",
        "alpaca": "אלפקה",
        "alpacas": "אלפקות",
        "anaconda": "אנקונדה",
        "anacondas": "אנקונדות",
        "ant": "נמלה",
        "ants": "נמלים",
        "antelope": "אנטילופה",
        "antelopes": "אנטילופות",
        "armadillo": "ארמדיל",
        "armadillos": "ארמדילים",
        "baboon": "בבון",
        "baboons": "בבונים",
        "bat": "עטלף",
        "bats": "עטלפים",
        "bear": "דוב",
        "bears": "דובים",
        "beast": "חיה",
        "bee": "דבורה",
        "bees": "דבורים",
        "beetle": "חיפושית",
        "beetles": "חיפושיות",
        "buffalo": "תאו",
        "buffalos": "תאואים",
        "butterfly": "פרפר",
        "butterflies": "פרפרים",
        "camel": "גמל",
        "camels": "גמלים",
        "cat": "חתול",
        "cats": "חתולים",
        "caterpillar": "זחל",
        "caterpillars": "זחלים",
        "cheetah": "ברדלס",
        "cheetahs": "ברדלסים",
        "chicken": "תרנגולת",
        "chickens": "תרנגולות",
        "chimpanzee": "שימפנזה",
        "chimpanzees": "שימפנזים",
        "chinchilla": "צ'ינצ'ילה",
        "chinchillas": "צ'ינצ'ילות",
        "chipmunk": "סנאי",
        "cow": "פרה",
        "cows": "פרות",
        "cobra": "קוברה",
        "cobras": "קוברות",
        "crab": "סרטן",
        "crabs": "סרטנים",
        "cricket": "צרצר",
        "crickets": "צרצרים",
        "crocodile": "תנין",
        "crocodiles": "תנינים",
        "crow": "עורב",
        "crows": "עורבים",
        "deer": "אייל",
        "dog": "כלב",
        "dogs": "כלבים",
        "dolphin": "דולפין",
        "dolphins": "דולפינים",
        "donkey": "חמור",
        "donkeys": "חמורים",
        "dove": "יונה",
        "doves": "יונים",
        "dragon": "דרקון",
        "dragonfly": "שפירית",
        "dragonflies": "שפיריות",
        "duck": "ברווז",
        "ducks": "ברווזים",
        "dinosaur": "דינוזואר",
        "dinosaurs": "דינוזוארים",
        "eagle": "נשר",
        "eagles": "נשרים",
        "elephant": "פיל",
        "elephants": "פילים",
        "falcon": "בז",
        "falcons": "בזים",
        "ferret": "חמוס",
        "ferrets": "חמוסים",
        "fish": "דג",
        "firefly": "גחלילית",
        "fireflies": "גחליליות",
        "flamingo": "פלמינגו",
        "flamingos": "פלמינגואים",
        "fox": "שועל",
        "foxes": "שועלים",
        "frog": "צפרדע",
        "frogs": "צפרדעים",
        "giraffe": "ג'ירפה",
        "giraffes": "ג'ירפות",
        "goat": "עז",
        "goats": "עזים",
        "goose": "אווז",
        "geese": "אווזים",
        "gorilla": "גורילה",
        "gorillas": "גורילות",
        "goldfish": "דג זהב",
        "grasshopper": "חגב",
        "grasshoppers": "חגבים",
        "grizzly": "דוב גריזלי",
        "hamster": "אוגר",
        "hamsters": "אוגרים",
        "hawk": "נץ",
        "hawks": "נצים",
        "hedgehog": "קיפוד",
        "hedgehogs": "קיפודים",
        "hippo": "היפופוטם",
        "hippos": "היפופוטמים",
        "hippopotamus": "היפופוטם",
        "horse": "סוס",
        "horses": "סוסים",
        "hyena": "צבוע",
        "hyenas": "צבועים",
        "ibex": "יעל",
        "ibexes": "יעלים",
        "iguana": "איגואנה",
        "iguanas": "איגואנות",
        "jaguar": "יגואר",
        "jaguars": "יגוארים",
        "jellyfish": "מדוזה",
        "kangaroo": "קנגורו",
        "kangaroos": "קנגורואים",
        "koala": "קואלה",
        "koalas": "קואלות",
        "leopard": "נמר",
        "leopards": "נמרים",
        "lemur": "למור",
        "lemurs": "למורים",
        "lice": "כינים",
        "lion": "אריה",
        "lions": "אריות",
        "lizard": "לטאה",
        "lizards": "לטאות",
        "lobster": "לובסטר",
        "lobsters": "לובסטרים",
        "llama": "למה",
        "llamas": "למות",
        "mole": "חפרפרת",
        "moles": "חפרפרות",
        "monkey": "קוף",
        "monkeys": "קופים",
        "mongoose": "נמיה",
        "mongooses": "נמיות",
        "mosquito": "יתוש",
        "mosquitoes": "יתושים",
        "moth": "עש",
        "mouse": "עכבר",
        "mice": "עכברים",
        "nightingale": "זמיר",
        "nightingales": "זמירים",
        "octopus": "תמנון",
        "octopuses": "תמנונים",
        "ostrich": "יען",
        "ostriches": "יענים",
        "otter": "לוטרה",
        "otters": "לוטרות",
        "owl": "ינשוף",
        "owls": "ינשופים",
        "ox": "שור",
        "oxen": "שוורים",
        "panda": "פנדה",
        "pandas": "פנדות",
        "parrot": "תוכי",
        "parrots": "תוכים",
        "peacock": "טווס",
        "peacocks": "טווסים",
        "pelican": "שקנאי",
        "pelicans": "שקנאים",
        "penguin": "פינגווין",
        "penguins": "פינגווינים",
        "pig": "חזיר",
        "pigs": "חזירים",
        "pigeon": "יונה",
        "pigeons": "יונים",
        "Penguin": "פינגווין",
        "Penguins": "פינגווינים",
        "platypus": "ברווזן",
        "platypuses": "ברווזנים",
        "porcupine": "דורבן",
        "porcupines": "דורבנים",
        "puppy": "גור כלבים",
        "rabbit": "ארנב",
        "rabbits": "ארנבים",
        "raccoon": "דביבון",
        "raccoons": "דביבונים",
        "rat": "עכברוש",
        "rats": "עכברושים",
        "raven": "עורב",
        "ravens": "עורבים",
        "reindeer": "אייל",
        "rhino": "קרנף",
        "rhinos": "קרנפים",
        "scorpion": "עקרב",
        "scorpions": "עקרבים",
        "sea_lion": "אריה ים",
        "sea_lions": "אריות ים",
        "seal": "כלב ים",
        "seals": "כלבי ים",
        "seahorse": "סוסון ים",
        "seahorses": "סוסוני ים",
        "sea_urchin": "קיפוד ים",
        "sea_urchins": "קיפודי ים",
        "seagull": "שחף",
        "seagulls": "שחפים",
        "shark": "כריש",
        "sharks": "כרישים",
        "sheep": "כבשה",
        "skunk": "בואש",
        "skunks": "בואשים",
        "sloth": "עצלן",
        "sloths": "עצלנים",
        "snail": "חילזון",
        "snails": "חילזונות",
        "snake": "נחש",
        "snakey": "נחשי",
        "snakes": "נחשים",
        "songbird": "ציפור שיר",
        "songbirds": "ציפורי שיר",
        "sparrow": "דרור",
        "sparrows": "דרורים",
        "spider": "עכביש",
        "spiders": "עכבישים",
        "squid": "דיונון",
        "squids": "דיונונים",
        "squirrel": "סנאי",
        "squirrels": "סנאים",
        "starfish": "כוכב ים",
        "stingray": "טריגון",
        "stingrays": "טריגונים",
        "swan": "ברבור",
        "swans": "ברבורים",
        "swordfish": "דג חרב",
        "termite": "טרמיט",
        "termites": "טרמיטים",
        "tiger": "טיגריס",
        "tigers": "טיגריסים",
        "toad": "קרפדה",
        "toads": "קרפדות",
        "toucan": "טוקן",
        "toucans": "טוקנים",
        "turtle": "צב",
        "turtles": "צבים",
        "unicorn": "חד קרן",
        "unicorns": "חדי קרן",
        "walrus": "סוס ים",
        "walruses": "סוסי ים",
        "wasp": "צרעה",
        "wasps": "צרעות",
        "whale": "לוויתן",
        "whales": "לוויתנים",
        "wolf": "זאב",
        "wolves": "זאבים",
        "zebra": "זברה",
        "zebras": "זברות"
    },

    "Transport": {
        "ambulance": "אמבולנס",
        "ambulances": "אמבולנסים",
        "car": "מכונית",
        "cars": "מכוניות",
        "bus": "אוטובוס",
        "buses": "אוטובוסים",
        "train": "רכבת",
        "trains": "רכבות",
        "truck": "משאית",
        "trucks": "משאיות",
        "van": "וואן",
        "vans": "וואנים",
        "taxi": "מונית",
        "taxis": "מוניות",
        "motorcycle": "אופנוע",
        "motorcycles": "אופנועים",
        "bike": "אופניים",
        "bikes": "אופניים",
        "bicycle": "אופניים",
        "bicycles": "אופניים",
        "scooter": "קטנוע",
        "scooters": "קטנועים",
        "skateboard": "סקייטבורד",
        "skateboards": "סקייטבורדים",
        "subway": "רכבת תחתית",
        "subways": "רכבות תחתיות",
        "tram": "חשמלית",
        "trams": "חשמליות",
        "metro": "מטרו",
        "metros": "מטרו",
        "ferry": "מעבורת",
        "ferries": "מעבורות",
        "boat": "סירה",
        "boats": "סירות",
        "ship": "ספינה",
        "ships": "ספינות",
        "yacht": "יאכטה",
        "yachts": "יאכטות",
        "canoe": "קאנו",
        "canoes": "קאנו",
        "kayak": "קיאק",
        "kayaks": "קיאקים",
        "helicopter": "מסוק",
        "helicopters": "מסוקים",
        "plane": "מטוס",
        "planes": "מטוסים",
        "airplane": "מטוס",
        "airplanes": "מטוסים",
        "jet": "מטוס סילון",
        "jets": "מטוסי סילון",
        "glider": "דאון",
        "gliders": "דאונים",
        "spaceship": "חללית",
        "spaceships": "חלליות",
        "rocket": "טיל",
        "rockets": "טילים",
        "hovercraft": "רחפת",
        "hovercrafts": "רחפות",
        "minivan": "מיניוואן",
        "minivans": "מיניוואנים",
        "pickup": "טנדר",
        "pickups": "טנדרים",
        "suv": "רכב שטח",
        "suvs": "רכבי שטח",
        "lorry": "משאית",
        "lorries": "משאיות",
        "trolley": "עגלה",
        "trolleys": "עגלות",
        "rickshaw": "ריקשה",
        "rickshaws": "ריקשות",
        "wagon": "עגלה",
        "wagons": "עגלות",
        "caravan": "קרוואן",
        "caravans": "קרוואנים",
        "camper": "קרוואן",
        "campers": "קרוואנים",
        "motorhome": "קרוואן",
        "motorhomes": "קרוואנים",
        "taxicab": "מונית",
        "taxicabs": "מוניות",
        "sailboat": "סירת מפרש",
        "sailboats": "סירות מפרש",
        "container_ship": "אוניית מכולות",
        "container_ships": "אוניות מכולות",
        "cargo_ship": "אוניית משא",
        "cargo_ships": "אוניות משא",
        "freight_train": "רכבת משא",
        "freight_trains": "רכבות משא",
        "bullet_train": "רכבת מהירה",
        "bullet_trains": "רכבות מהירות",
        "electric_car": "רכב חשמלי",
        "electric_cars": "רכבים חשמליים",
        "hybrid_car": "רכב היברידי",
        "hybrid_cars": "רכבים היברידיים",
        "self-driving_car": "רכב אוטונומי",
        "self-driving_cars": "רכבים אוטונומיים",
        "electric_scooter": "קורקינט חשמלי",
        "electric_scooters": "קורקינטים חשמליים",
        "electric_bike": "אופניים חשמליים",
        "electric_bikes": "אופניים חשמליים",
        "sail": "להפליג",
        "drive": "לנהוג",
        "driver": "נהג",
        "drivers": "נהגים",
        "passenger": "נוסע",
        "passengers": "נוסעים",
        "pilot": "טייס",
        "pilots": "טייסים",
        "mechanic": "מכונאי",
        "mechanics": "מכונאים",
        "chauffeur": "נהג פרטי",
        "chauffeurs": "נהגים פרטיים",
        "navigator": "נווט",
        "navigators": "נווטים",
        "station": "תחנה",
        "stations": "תחנות",
        "terminal": "טרמינל",
        "terminals": "טרמינלים",
        "runway": "מסלול המראה",
        "runways": "מסלולי המראה",
        "port": "נמל",
        "ports": "נמלים",
        "harbor": "מעגן",
        "harbors": "מעגנים",
        "garage": "מוסך",
        "garages": "מוסכים",
        "highway": "כביש מהיר",
        "highways": "כבישים מהירים",
        "road": "כביש",
        "roads": "כבישים",
        "street": "רחוב",
        "streets": "רחובות",
        "lane": "נתיב",
        "lanes": "נתיבים",
        "avenue": "שדרה",
        "avenues": "שדרות",
        "intersection": "צומת",
        "intersections": "צמתים",
        "crosswalk": "מעבר חצייה",
        "crosswalks": "מעברי חצייה",
        "traffic_light": "רמזור",
        "traffic_lights": "רמזורים",
        "stop_sign": "תמרור עצור",
        "stop_signs": "תמרורי עצור",
        "roundabout": "כיכר תנועה",
        "roundabouts": "כיכרות תנועה",
        "bridge": "גשר",
        "bridges": "גשרים",
        "tunnel": "מנהרה",
        "tunnels": "מנהרות",
        "railway": "מסילת רכבת",
        "railways": "מסילות רכבת",
        "railroad": "פסי רכבת",
        "railroads": "פסי רכבת",
        "track": "מסילה",
        "tracks": "מסילות",
        "bike_lane": "שביל אופניים",
        "bike_lanes": "שבילי אופניים",
        "flight": "טיסה",
        "flights": "טיסות",
        "boarding_pass": "כרטיס עלייה למטוס",
        "boarding_passes": "כרטיסי עלייה למטוס",
        "ticket": "כרטיס",
        "tickets": "כרטיסים",
        "fare": "דמי נסיעה",
        "fares": "דמי נסיעה",
        "transport": "תחבורה",
        "transportation": "תחבורה",
        "delivery": "משלוח",
        "deliveries": "משלוחים",
        "freight": "מטען",
        "cargo": "מטען",
        "shipment": "משלוח",
        "shipments": "משלוחים",
        "commute": "נסיעה יומית",
        "commutes": "נסיעות יומיות",
        "journey": "מסע",
        "journeys": "מסעות",
        "landing": "נחיתה",
        "takeoff": "המראה",
        "takeoffs": "המראות",
        "boarding": "עלייה למטוס",
        "trip": "טיול",
        "trips": "טיולים",
        "travel": "נסיעה",
        "travels": "נסיעות",
        "transit": "מעבר",
        "route": "מסלול",
        "routes": "מסלולים",
        "itinerary": "מסלול נסיעה",
        "itineraries": "מסלולי נסיעה",
        "departure": "יציאה",
        "departures": "יציאות",
        "arrival": "הגעה",
        "arrivals": "הגעות",
        "delay": "עיכוב",
        "delays": "עיכובים",
        "schedule": "לוח זמנים",
        "schedules": "לוחות זמנים"
    }
}
