// This file maps all available question files for easy access
// Add new questions here as you create them

const questionsRegistry: Record<string, any> = {
  Heels: require("./Heels.json"),
  Jeans: require("./Jeans.json"),
  Sneakers: require("./Sneakers.json"),
  Skirts: require("./Skirts.json"),
  Scarf: require("./Scarf.json"),
  Shirt: require("./Shirt.json"),
  Glasses: require("./Glasses.json"),
  Home: require("./Home.json"),
  House: require("./House.json"),
  Mother: require("./Mother.json"),
  Sister: require("./Sister.json"),
  Car: require("./Car.json"),
  Streets: require("./Streets.json"),
  Road: require("./Road.json"),
  Street: require("./Street.json"),
  Boots: require("./Boots.json"),
  Gloves: require("./Gloves.json"),
  Cake: require("./Cake.json"),
  Ice: require("./Ice.json"),
  Watermelon: require("./Watermelon.json"),
  Love: require("./Love.json"),
  Tired: require("./Tired.json"),
  Scared: require("./Scared.json"),
  Feeling: require("./Feeling.json"),
  Brain: require("./Brain.json"),
  Eyes: require("./Eyes.json"),
  Fingers: require("./Fingers.json"),
  Mouth: require("./Mouth.json"),
  Candy: require("./Candy.json"),
  Cookie: require("./Cookie.json"),
  Daddy: require("./Daddy.json"),
  Sisters: require("./Sisters.json"),
  Score: require("./Score.json"),
  Throw: require("./Throw.json"),
  Team: require("./Team.json"),
  Ball: require("./Ball.json"),
  Winning: require("./Winning.json"),
  Tiger: require("./Tiger.json"),
  Butterfly: require("./Butterfly.json"),
  Lion: require("./Lion.json"),
  Bee: require("./Bee.json"),
  Pleased: require("./Pleased.json"),
  Confused: require("./Confused.json"),
  Cheer: require("./Cheer.json"),
  Captain: require("./Captain.json"),
  "Broken Heart": require("./Broken Heart.json"),
  Bleachers: require("./Bleachers.json"),
};

export default questionsRegistry;
