### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "jane_doe",
  "password": "securePassword123"
}

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "oran",
  "password": "securePassword124",
  "level": 1,
  "genres": ["rock", "pop"]
}

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "jane_doh",
  "password": "securePassword222"
}

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "jane_don",
  "password": "securePassword246",
  "level": 2,
  "genres": ["pop"]
}

### Get user details by ID
GET http://localhost:3000/api/users/677eb0296b8d36d5eacf6b53

### 1. הוספת שיר לרשימת מועדפים
PATCH http://localhost:3000/api/users/68f22ba7187347a8f2bdd95f/favorites
Content-Type: application/json

{
  "title": "Shap You",
  "artist": "Ed Sheeran"
}

### 1. הוספת שיר לרשימת מועדפים
PATCH http://localhost:3000/api/users/6918a78ef2223bf071c42c49/favorites
Content-Type: application/json

{
  "songId": "69189429a3b605871525da35"
}

###

### 2. שינוי רמת קושי
PATCH http://localhost:3000/api/users/6880f447647cf2a21f291ee4/level
Content-Type: application/json

{
  "level": 1
}

###

### 3. עדכון ז'אנרים
PATCH http://localhost:3000/api/users/68f24401e72000776cf47a74/genres
Content-Type: application/json

{
  "genres": ["jazz", "electronic"]
}

###

### 4. עדכון רשימת מילים נכונות וטעויות
PATCH http://localhost:3000/api/users/6880f447647cf2a21f291ee4/history
Content-Type: application/json

{
  "correctWords": ["dog", "cat", "sky"],
  "mistakenWords": ["apple", "cat"]
}


### Get user details by username
PATCH http://localhost:3000/api/users/68f22ba7187347a8f2bdd95f/history
Content-Type: application/json

{
  "correctWords": ["heels","skirts","sneakers"],
  "mistakenWords": ["jeans"]
}

### Get user details by ID
POST http://localhost:3000/api/recommendations/only-new
Content-Type: application/json

{
  "user": {
    "wordHistory": ["jeans", "heels", "skirts", "sneakers"],
    "genre": ["rock", "pop"],
    "level": 1
  },
  "category": "Clothing"
}

### Get user details by username
GET http://localhost:3000/api/users/by-username/

### Get user details by ID
GET http://localhost:3000/api/users/68c17208dcc6dad7b61920e0

