### Create a new song
POST http://localhost:3000/api/songs
Content-Type: application/json

{
    "name": "you belong with me",
    "artist": "taylor swift",
    "genre": "Pop",
    "categories": ["Clothing", "Sports"],
    "category_words": [
        ["jeans", "heels", "skirts", "sneakers", "1"],
        ["bleachers", "cheer", "captain", "2"]
    ],
    "picture": "../myApp/assets/artists/taylor_swift.jpg"
}

### Create a new song
GET http://localhost:3000/api/songs


### get favorite suggestions for a user
GET  http://localhost:3000/api/songs/6918a78ef2223bf071c42c49/favorite-suggestions
Content-Type: application/json  
X-User-Id: 6918a78ef2223bf071c42c49