// myApp/assets/audios/audioMap.ts
export const audioMap: Record<string, any> = {
  "20th century boy": require("./audios/20th Century Boy.mp3"),
  "23": require("./audios/23.mp3"),
  "a little something refreshing": require("./audios/A Little Something Refreshing.mp3"),
  "a little something refreashing": require("./audios/A Little Something Refreshing.mp3"),
  "airplanes": require("./audios/Airplanes.mp3"),
  "all too well": require("./audios/all too well.mp3"),
  "animals": require("./audios/Animals.mp3"),
  "bad obsession": require("./audios/Bad Obsession.mp3"),
  "believer": require("./audios/Believer.mp3"),
  "bette davis eyes": require("./audios/bette davis eyes.mp3"),
  "big pimpin'": require("./audios/Big Pimpin'.mp3"),
  "breakdown": require("./audios/Breakdown.mp3"),
  "breathe": require("./audios/breathe.mp3"),
  "breathless": require("./audios/breathless.mp3"),
  "brought up that way": require("./audios/brought up that way.mp3"),
  "cellophane": require("./audios/Cellophane.mp3"),
  "change": require("./audios/change.mp3"),
  "cheetah": require("./audios/cheetah.mp3"),
  "come back...be here": require("./audios/come back...be here.mp3"),
  "dance": require("./audios/Dance.mp3"),
  "dancer": require("./audios/Dancer.mp3"),
  "dark side of the moon": require("./audios/Dark side of the moon.mp3"),
  "death on two legs": require("./audios/Death on two Legs.mp3"),
  "drive": require("./audios/drive.mp3"),
  "drain you": require("./audios/Drain You.mp3"),
  "drunk in love": require("./audios/drunk in love.mp3"),
  "feeling good": require("./audios/Feeling Good.mp3"),
  "flawless": require("./audios/flawless.mp3"),
  "freedom": require("./audios/freedom.mp3"),
  "goodbye angels": require("./audios/Goodbye Angels.mp3"),
  "he dark side of the moon": require("./audios/Dark side of the moon.mp3"),
  "i am the walrus": require("./audios/I Am The Walrus.mp3"),
  "i don't give a": require("./audios/I Don't Give A.mp3"),
  "i'm your gun": require("./audios/I'm Your Gun.mp3"),
  "if i ruled the world": require("./audios/If I Ruled The World.mp3"),
  "in my blood": require("./audios/In My Blood.mp3"),
  "inmates": require("./audios/Inmates.mp3"),
  "jealous": require("./audios/jealous.mp3"),
  "justify my love": require("./audios/Justify My Love.mp3"),
  "king of pain": require("./audios/king of pain.mp3"),
  "last caress": require("./audios/Last Caress.mp3"),
  "little things": require("./audios/Little Things.mp3"),
  "locomotive": require("./audios/Locomotive.mp3"),
  "lost cause": require("./audios/Lost Cause.mp3"),
  "love": require("./audios/Love.mp3"),
  "madonna score": require("./audios/Madonna Score.mp3"),
  "mama kin": require("./audios/Mama Kin.mp3"),
  "marry the night": require("./audios/marry the night.mp3"),
  "milk milk lemonade": require("./audios/milk milk lemonade.mp3"),
  "modern times rock 'n' roll": require("./audios/Modern Times Rock 'n' Roll.mp3"),
  "modern times rock'n'roll": require("./audios/Modern Times Rock 'n' Roll.mp3"),
  "more of that jazz": require("./audios/More Of That Jazz.mp3"),
  "move to the city": require("./audios/Move To The City.mp3"),
  "my fairy king": require("./audios/My Fairy King.mp3"),
  "nobody home": require("./audios/Nobody Home.mp3"),
  "our song": require("./audios/our song.mp3"),
  "pablow the blowfish": require("./audios/Pablow The Blowfish.mp3"),
  "rocket queen": require("./audios/Rocket Queen.mp3"),
  "roar": require("./audios/roar.mp3"),
  "round are way": require("./audios/Round Are Way.mp3"),
  "secret": require("./audios/Secret.mp3"),
  "serve the servants": require("./audios/Serve The Servants.mp3"),
  "she's electric": require("./audios/She's Electric.mp3"),
  "so what": require("./audios/So What.mp3"),
  "speak to me": require("./audios/Speak To Me.mp3"),
  "score": require("./audios/Score.mp3"),
  "sucker for pain": require("./audios/Sucker for Pain.mp3"),
  "sweet life": require("./audios/Sweet Life.mp3"),
  "take you out": require("./audios/take you out.mp3"),
  "tangerine": require("./audios/Tangerine.mp3"),
  "that's life": require("./audios/that's life.mp3"),
  "the beast within": require("./audios/The Beast Within.mp3"),
  "the pit": require("./audios/The Pit.mp3"),
  "the unknown": require("./audios/The Unknown.mp3"),
  "wait your turn": require("./audios/Wait Your Turn.mp3"),
  "we turn red": require("./audios/We Turn Red.mp3"),
  "whatever it takes": require("./audios/Whatever It Takes.mp3"),
  "who owns my heart": require("./audios/Who Owns My Heart.mp3"),
  "you belong with me": require("./audios/you belong with me.mp3"),
};
