// myApp/assets/audios/audioMap.ts
export const audioMap: Record<string, any> = {
  "all too well": require("./audios/all too well.mp3"),
  "bette davis eyes": require("./audios/bette davis eyes.mp3"),
  "breathe": require("./audios/breathe.mp3"),
  "breathless": require("./audios/breathless.mp3"),
  "brought up that way": require("./audios/brought up that way.mp3"),
  "change": require("./audios/change.mp3"),
  "cheetah": require("./audios/cheetah.mp3"),
  "come back...be here": require("./audios/come back...be here.mp3"),
  "drive": require("./audios/drive.mp3"),
  "drunk in love": require("./audios/drunk in love.mp3"),
  "flawless": require("./audios/flawless.mp3"),
  "freedom": require("./audios/freedom.mp3"),
  "jealous": require("./audios/jealous.mp3"),
  "king of pain": require("./audios/king of pain.mp3"),
  "marry the night": require("./audios/marry the night.mp3"),
  "milk milk lemonade": require("./audios/milk milk lemonade.mp3"),
  "our song": require("./audios/our song.mp3"),
  "roar": require("./audios/roar.mp3"),
  "take you out": require("./audios/take you out.mp3"),
  "that's life": require("./audios/that's life.mp3"),
  "you belong with me": require("./audios/you belong with me.mp3"),
};